alces-software/alces-flight-center

spec/models/application_record_spec.rb

This PR follows on from #30 with a couple of tweaks to the generated model permissions tests. In particular this:
a. always skips the generated test when the model is an STI base class;
b. changes how we iterate through all app models to include STI subclasses, so these are also covered by tests.

Improve generated permissions tests

---

app/models/component.rb
spec/factories.rb
spec/models/component_spec.rb

When a new component is created, it will automatically create the
default expansions. This is done by reading the DefaultExpansions
from ComponentMake.
The issue with this approach is the :ports, :slot, and :expansion_type
attributes must be manually stated. Because the Expansions use STI,
not all the attributes are ported across.
In particular the id fields must not be copied as this could easily
make an invalid ComponentExpansion. Also the :type field must not be
copied as this will screw around with the STI.
I am open to suggestions on how to do this better. However for the
time being the list needs to be maintained. There is a test for this
behaviour so future changes should be detected.

Create ComponentExpansion's based off defaults

---

app/controllers/asset_records_controller.rb
app/decorators/application_decorator.rb
app/decorators/asset_record_decorator.rb
app/decorators/component_decorator.rb
app/decorators/component_group_decorator.rb
app/models/component_type.rb
app/models/concerns/has_asset_record.rb
app/views/asset_records/edit.html.erb
app/views/component_groups/show.html.erb
app/views/components/show.html.erb
app/views/partials/_asset_record_table.html.erb
config/routes.rb
spec/features/asset_record.rb
spec/models/component_spec.rb
spec/models/concerns/has_asset_record_spec.rb

The majority of this PR is associated with creating the asset_record partial and embedding a form into it. By creating a partial, the majority of the view associated with showing and editing the asset record can be generalised.
The `HasAssetRecord` concern has also been simplified now that less code is dependent on it. The appropriate changes have been made in the view as well.
A `AssetRecordDecorator` has been created to assist in the routing. As multiple models use the partial, the inbuilt rails route helpers couldn't be used. Please see https://github.com/alces-software/alces-flight-center/commit/169622436dd23db23b3ad9ee94f2f7f9c849c65f for more details.
Please note this PR does not implement the updating of the asset records. Due to the complexity of the asset_record updating it is …

Create the edit page for asset record and the associated routes

---

app/javascript/packs/View/Fields.elm

The previous behaviour worked fine in Chrome and Firefox, which fire an 'input' event whenever a `select` is changed. However IE and Edge don't do this, because apparently the spec is not entirely clear that they should do so; therefore when any select in the form was changed in these browsers no 'input' event would be fired and so no messages would be sent, and so the form appeared not to respond to this interaction.
The solution is to have the `select`s listen for any 'change' event, which appears to cause the desired messages to be sent in all these browsers.
Relevant issue: https://github.com/elm-lang/html/issues/71.
Relevant comment on this issue with suggested fix:
https://github.com/elm-lang/html/issues/71#issuecomment-242363580.

Fix selects not causing messages in some browsers (fixes #39)

---

app/controllers/asset_records_controller.rb
app/models/concerns/has_asset_record.rb
spec/models/concerns/has_asset_record_spec.rb

This PR is based on #35, please merge it first.
Once the edit form has been submitted, the `AssetRecordsController` passes it onto the `HasAssetRecord` which does the update. This way the update code can be reused in multiple places.
The logic behind the update is based on the following used by the admin interface. The admin interface has not been switched over to use the module as asset records will likely be edited through the new interface. This means the old admin update code will likely be removed completely at a future date.
https://github.com/alces-software/alces-flight-center/blob/530e4f9f155ce45eaf7c16f64bcad407ba7788e0/app/models/concerns/admin_config/shared/editable_asset_record_fields.rb#L109-L133
Unfortunately the spec for the admin code could not be salvaged as it relies on …

Update the asset records from the submitted form

---

app/controllers/asset_records_controller.rb
app/models/component_make.rb
app/models/concerns/has_asset_record.rb
app/views/clusters/show.html.erb
app/views/component_groups/show.html.erb
app/views/partials/_asset_record_table.html.erb
app/views/partials/_components_table.html.erb
spec/models/concerns/has_asset_record_spec.rb

Based on #36, please merge it first.
A few additional `UI` features have been added to the edit `AssetRecord` table.
1. It no longer autofills the `asset_record_table` with the parent/ higher values. Instead the parent values are now a placeholder. This required the `HasAssetRecordConcern` to be modified as empty strings no longer mean delete in all circumstances. https://github.com/alces-software/alces-flight-center/pull/38/commits/264fcb822fe1447401db97f61cd11cb3a8f4815d
1. Asset records that can only be set at the component level are greyed out at the group level. Title text has been set to explain this.
1. The `ComponentMake` can now be changed for the `ComponentGroup` based on the previous `ComponentType`.
1. The `Components` are now displayed on the `ComponentGroup` page.

Additional UI features for `AssetRecord` table

---

db/data_migrations/20180201182222_add_back_missing_issue_categories.rb

We recently changed Issues to be related to Services, and make Issue
Categories not required (in order to make the Case form read more
intuitively and not include unnecessary Category fields containing only
one or two Issues). At some point in this process we lost the
relationship between Issues and Categories that we did still want to
keep, to split up the Issues for the 'HPC Environment' Service as there
are quite a lot of these. This migration adds these back appropriately.
Trello: https://trello.com/c/qpgoO4WZ/151-categories-dont-exist-correctly-in-production-data.

Add migration to add back missing Issue Categories

---

app/decorators/asset_record_decorator.rb
app/models/concerns/has_asset_record.rb
app/views/cases/_cases_table.html.erb
app/views/clusters/show.html.erb
app/views/components/show.html.erb
app/views/partials/_asset_record_table.html.erb
app/views/partials/_card_header_nav.html.erb
app/views/partials/_edit_submit_button.html.erb
app/views/partials/_expansion_table.html.erb
db/seeds/development/data.seeds.rb
spec/models/concerns/has_asset_record_spec.rb

This PR is the first step of implementing the expansions. It focuses on updating the views to be able to show the expansions data as it is added/ updated.
It shares a commit history with #43 and should be merged first.
It DRY's up how the header bar of the tables is being created using a partial (`'partials/card_header_nav'`). For the most part, supplying a `title` to the partial is enough for it to be rendered. It does however accommodate list items to be rendered with it, as done in a few locations.
An expansions table has been added to the `component` page. This table has been inspired by `asset_record_table` and shall function in much the same way. In order for the table to be displayed, seed data has been added.
Both `asset_records` and `expansions` table need to toggle the …

Dry up the views for adding the expansions table

---

config/routes.rb
spec/features/asset_record.rb

The tests where bad as they where from a non-logged in user which will always fail. However logged in users could access the routes to update the asset record.
This PR fixes the test and updates the routes.
It is based on #46. It should be merged before #43

Small bug fix making update asset record admin only

---

app/controllers/component_expansions_controller.rb
app/models/expansion.rb
app/views/component_expansions/edit.html.erb
app/views/partials/_expansion_table.html.erb
app/views/partials/_flash_alert.html.erb
config/routes.rb

Based on #47, please merge it first. This PR should be merged and then #43 is the final PR concerning expansions.
A new page has been added to edit component expansions. It preforms a bulk edit in which all the expansions for a single component can be edited at the same time.
All the expansions are otherwise updated independently, meaning if one update fails than the other updates still occur. Any errors will be flashed to the user.
Currently the only constraints are the port has to be a number. The constraints need to be updated to allow nil number of ports.

Add the `edit` and `update` action for `component_expansions`

---

app/controllers/component_expansions_controller.rb
app/helpers/application_helper.rb
app/views/cases/_cases_table.html.erb
app/views/component_expansions/edit.html.erb
app/views/partials/_asset_record_table.html.erb
app/views/partials/_edit_submit_button.html.erb
app/views/partials/_expansion_table.html.erb
config/routes.rb

Based on #38, please merge it first
This PR is a tad long as it contains a few internal changes to `AssetRecord` code. This is part breaking out the different form elements into `partials` and `decorators` (https://github.com/alces-software/alces-flight-center/commit/04d291c3b35fdfb8e092295b906c14d213d4948f, https://github.com/alces-software/alces-flight-center/commit/5d8a1581527c2cd7adab8c46eb98ab34b3dab31d, https://github.com/alces-software/alces-flight-center/commit/756a27c87ed99295f82dad9ea765cb448c09d7f7) and subsequent changes to how they function. This is to make it easier generate the different common features used by the forms.
There was also a bug fix in which any user could update the asset record due to a bad test. It has been fixed in …

Add page to create/edit/delete ComponentExpansions

---

app/assets/stylesheets/application.scss

When combined with `pointer-events: none` this makes this both more obvious and not hide navigation buttons. As suggested at https://alces.slack.com/archives/C72GT476Y/p1517835768000174.

Fix develop ribbon to always show

---

app/controllers/cases_controller.rb
app/decorators/case_decorator.rb
app/helpers/application_helper.rb
app/views/cases/_cases_table.html.erb
app/views/cases/show.html.erb
bin/import-production-data
config/routes.rb
spec/decorators/case_decorator_spec.rb
spec/features/cases_table_spec.rb
spec/helpers/application_helper_spec.rb

This PR adds a new Case page showing all user-relevant information for each Case, and then simplifies the Case table to be less busy and show less information, and link to this new page for each Case.
Trello: https://trello.com/c/dV0HHDRQ/156-show-subject-and-not-details-have-new-case-page-showing-all-case-info-including-details.

Case pages

---

config/initializers/sentry.rb

If a DSN isn't set (e.g. for running in development) then Sentry won't report errors. This is probably what we want when running on dev machines.

Make Sentry DSN configuration optional.

---

app/models/case.rb
app/models/cluster_log.rb
db/migrate/20180208121324_add_cluster_log.rb
db/schema.rb
spec/factories.rb
spec/models/cluster_log_spec.rb

This will allow "engineers" to log events against a cluster. It is directly linked to the cluster and thus the logs do not need to be associated with an open case. The `engineer` can be any flight centre admin user.
The `ClusterLog` can also be associated with cases. This is a many-many relationship to allow for flexibility. The only constraint is all the `cases` belong to the same cluster as the log itself. This is enforced at the model level.
A `cluster_log.related_ticket_numbers` method has not been included at this time. It is essence an alias of `cluster_log.cases.map(&:rt_ticket_id)` which is of similar length. The `RT` ids are likely going to be a view issue and not something required at the model level. Any form that needs to display the `RT_id` will also need the `id` which is …

Create the `ClusterLog` model

---

bin/backup-database
docs/backups.md

As requested by @mjtko, run the database backup script every 3 hours
rather than once per day to reduce the amount of data that could be lost
at any particular time.
This just involves updating the documentation and changing the file
names used for saving backups so backups on the same day do not
overwrite each other.

Create more frequent database backups

---

app/controllers/application_controller.rb
app/controllers/asset_records_controller.rb
app/controllers/cluster_logs_controller.rb
app/controllers/component_expansions_controller.rb
app/decorators/case_decorator.rb
app/models/cluster.rb
app/models/cluster_log.rb
app/views/cluster_logs/index.html.erb
app/views/clusters/show.html.erb
app/views/maintenance_windows/new.html.erb
config/routes.rb
spec/features/cluster_log.rb

This PR is based on #62, please merge it first
Most of this PR is reasonable straight forward. There was no major refactoring required in implementing the view. The `index` page is used to display all the logs for a cluster. `admins` also have an additional form (on the same page) to add a new log.

Create the route, view and controller for ClusterLog

---

app/models/cluster.rb
app/models/concerns/cluster_part.rb
app/models/concerns/has_maintenance_windows.rb
app/models/maintenance_window.rb
spec/models/maintenance_window_spec.rb
spec/shared_examples/maintenance_windows.rb

This is a small, self-contained PR which builds upon #75 (so merge that first). It just updates the `open_maintenance_windows` method, provided for all models which can have maintenance windows, to account for and exclude MaintenanceWindows in any of the 'finished' states which are now possible; some minor other tweaks need to do this are also included.

Only include unfinished maintenance windows when getting open maintenance windows

---

app/services/progress_maintenance_window.rb
spec/services/progress_maintenance_window_spec.rb

Based on #77. This PR implements a new object, `ProgressMaintenanceWindow`, which takes a MaintenanceWindow as an argument and then progresses its state or not as needed when its `progress` method is called, based on the current time and the `requested_start` and `requested_end` of the maintenance. This method also returns an appropriate message about this change or lack of it, so this can later be logged. Actually using this new object anywhere is still to come in a future PR.

Maintenance progression service

---

Gemfile
lib/tasks/generate.rake

Based on #78. This PR adds a small Rake task to generate the MaintenanceWindow state machine diagram. This serves 2 purposes:
1. allows us to do this slightly more simply with a single command;
2. allows me to get slightly more familiar with writing a Rake task, which I've not done before and will need for adding a larger task for progressing MaintenanceWindows (relevant resources if you're curious about Rake: https://martinfowler.com/articles/rake.html and https://rubysolutions.wordpress.com/2016/06/25/how-to-create-rake-tasks-in-rails-application/).

State machine diagram rake task

---

app/models/maintenance_window.rb
db/data_migrations/20180223150748_update_existing_maintenance_windows.rb
spec/models/maintenance_window_spec.rb

This PR adds a data migration to update all existing MaintenanceWindows to be in the new format Flight Center expects. The main commit doing this is https://github.com/alces-software/alces-flight-center/commit/43962b0adc9156d3b93f000016f049c6d7630ae1, and in order to do this I also needed to add a way to skip commenting on an RT ticket when a MaintenanceWindow transitions, which is done in the earlier commits. Based on #82.

Migrate existing maintenance windows to new format

---

app/controllers/application_controller.rb
app/helpers/application_helper.rb
app/views/layouts/application.html.erb
app/views/partials/_nav_bar.html.erb
app/views/partials/_nav_link.html.erb
spec/features/nav_bar_spec.rb
spec/requests/navigation_variable_assignments_spec.rb

Based on #85, either merge it first or skip it and merge this one. This PR fixes the errors in the previous PR.
The rendering of the nav bar has been completely overhauled to rely on the scope. This means other controllers can now set instance variables without having to worry about affecting the navigation. The nav bar has been broken out into its own partial template. The nav links also have there own partial as this prevents duplication of the code.
When rendering a nav link, the `text`, `path` and `icon` for the link are required. Alternatively, a `model` can be provided which will implicitly set the `text` and `path`.
Things get a bit tricky when trying to set the active link. Previously this was done with a bunch of logic, which isn't idea as it is more likely to be bug prone. …

Clean up the rendering of the nav bar

---

app/controllers/application_controller.rb
spec/requests/navigation_variable_assignments_spec.rb

Previously a bunch of navigation variables need to be set in order for the navigation bar to constructed. The problem with this is it makes it hard for other controllers to know if the nav variable is the model for the current page.
Instead a `scope` variable has been set instead. This makes it clear which model belongs to the current page and can be used by other controller (e.g. `LogController` - eventually). This PR implements the `scope` and updates the navigation variable spec.
Almost all the extraneous variables have been removed with exception of the `cluster_part` which is still required.
This PR does completely break the nav bar. This will be fixed in the next PR which focuses on refactoring it.

Implement a scope to be used by the nav bar

---

app/models/maintenance_window.rb
docs/release-process.md
lib/tasks/cron.rake
lib/tasks/maintenance_windows.rake
spec/lib/tasks/cron_spec.rb
spec/lib/tasks/maintenance_windows_spec.rb
spec/models/maintenance_window_spec.rb
spec/spec/support/spec_utils_spec.rb
spec/support/shared_contexts/rake.rb

This PR:
- implements a Rake task which will progress all unfinished maintenance windows;
- sets up a generic Rake task which will run every minute, to run the above and any other future similar tasks we might have;
- sets up a means of testing these and other Rake tasks;
- documents how to install the `cron` Rake task for our next deploy.
Based on #87.

Scheduled maintenance window progression

---

app/models/maintenance_window.rb
spec/models/maintenance_window_spec.rb

This PR implements `respond_to?` for the `MaintenanceWindow` class, which is the best practice when `method_missing` is implemented and helps avoid potential odd problems when these give inconsistent results (which is what prompted me to do this after having issues in a later PR). Some related refactoring is also included. Based on #88.

Implement `respond_to?` for MaintenanceWindows

---

app/controllers/maintenance_windows_controller.rb
app/decorators/maintenance_window_decorator.rb
app/models/maintenance_window.rb
app/views/clusters/show.html.erb
app/views/maintenance_windows/_unconfirmed_buttons.html.erb
config/routes.rb
spec/decorators/maintenance_window_decorator_spec.rb
spec/features/maintenance_windows_spec.rb
spec/models/maintenance_window_spec.rb

This PR updates the maintenance table shown on the Cluster page to show new data and support new actions, following implementing the new maintenance window system. This includes:
- showing the requested time period for each requested/scheduled maintenance window;
- showing a cancel maintenance button to admins;
- showing a reject maintenance button to contacts;
- various related refactoring behind the scenes.
Based on #89.

Update maintenance table

---

app/models/maintenance_window.rb
app/models/maintenance_window_state_transition.rb
spec/decorators/maintenance_window_decorator_spec.rb
spec/models/maintenance_window_spec.rb
spec/models/maintenance_window_state_transition_spec.rb

This PR validates that the user who initiated a MaintenanceWindow transition is of the appropriate type, i.e. only admins can request or cancel maintenance and only users can reject it (confirming maintenance will be only allowed by users later, once https://github.com/alces-software/alces-flight-center/issues/73 has been implemented). Also included is some refactoring of the transition tests and a fix so MaintenanceWindows do not blow up when an invalid transition occurs.
Based on #90.

Validate MaintenanceWindow transition user

---

app/decorators/application_decorator.rb
app/decorators/case_decorator.rb
app/decorators/maintenance_window_decorator.rb
app/models/cluster.rb
app/models/concerns/cluster_part.rb
app/models/concerns/has_maintenance_windows.rb
app/models/maintenance_notifier.rb
app/models/maintenance_window.rb
app/views/clusters/show.html.erb
app/views/logs/index.html.erb
spec/decorators/application_decorator_spec.rb
spec/decorators/case_decorator_spec.rb
spec/features/maintenance_windows_spec.rb
spec/models/cluster_spec.rb
spec/models/component_spec.rb
spec/models/maintenance_window_spec.rb
spec/models/service_spec.rb
spec/spec_helper.rb
spec/support/shared_examples/maintenance_windows.rb

This PR contains the final fixes and tweaks for the new maintenance system (hopefully, and barring issues brought up from the other outstanding PRs). See commits for full details, but in particular this includes:
- updates to the icons shown for things with upcoming/in progress maintenance to account for the new states and process;
- updates to the comments made on RT tickets for maintenance transitions to be more consistent and accurate;
- various updates to consistently refer to maintenance as finished vs unfinished, rather than sometimes also referring to open vs closed;
- some other refactoring and tweaks for minor related things I've spotted.
Based on #91. This should complete #42 / https://trello.com/c/L2GTfslB/173-maintenance-period-extensions.

Final new maintenance system tweaks

---

app/models/case.rb
app/models/case/associated_model_validator.rb
app/models/case/issue_validator.rb
app/models/case/validator.rb
app/models/cluster.rb
spec/models/case/validation_spec.rb

This PR fixes an issue where Cases could become invalid if their associated model's `support_type` is later changed; this could then cause an error in the UI in some circumstances. See https://github.com/alces-software/alces-flight-center/commit/ec819c7f74a4610e849e71c4278c40d4b7a060b3 for an explanation of the issue and fix; the other commits here are just refactoring following this change. The diff here is quite large but most of this is just churn due to renaming/splitting some files and changing indentation.
Trello: https://trello.com/c/EFipx2DP/186-fix-error-when-admin-views-all-cases-page-and-some-cases-have-since-become-invalid-due-to-their-associated-models-support-type-c.

Fix invalid cases when model support type changed

---

fixtures/vcr_cassettes/rt_add_ticket_correspondence.yml
fixtures/vcr_cassettes/rt_create_ticket.yml
fixtures/vcr_cassettes/rt_show_ticket.yml

Nothing interesting here, just updating the VCR fixtures, which automatically expire once a month. You'll need to have this merged, and other things rebased on it, for all tests to run successfully (unless you have valid credentials for everything set up, in which case it shouldn't matter).

Automatically update all VCR fixtures

---

app/models/maintenance_window.rb
db/migrate/20180308175322_track_requested_start_and_end_in_transitions.rb
db/schema.rb
spec/models/maintenance_window_spec.rb

The values for `requested_start` and `requested_end` may soon potentially change for a MaintenanceWindow at different points; in particular a site contact will soon be able to  change these values when they confirm some maintenance. Therefore we now want to track these values as they change in the MaintenanceWindow transition model so that we do not lose this potentially useful information.
One small step towards https://trello.com/c/k81APmbi/191-expired-maintenance-should-still-show-in-table-users-can-always-change-requested-start-and-end-date-when-confirming; based on #99.

Track `requested_start` and `requested_end` in MaintenanceWindow transitions

---

app/models/maintenance_window.rb
spec/models/maintenance_window_spec.rb
spec/services/progress_maintenance_window_spec.rb

This PR adds various validations for the MaintenanceWindow `requested_start` and `requested_end` validations, to ensure certain invariants about these properties hold:
- `requested_start` should always be before `requested_end`;
- `requested_start` and `requested_end` cannot be in the past, apart from in certain 'finished' states for a MaintenanceWindow to avoid every saved MaintenanceWindow eventually becoming invalid which would likely cause us future problems.
Adding these validations now became particularly important as non-admin users will soon be able to change these fields, so we want to be more robust when given bad data to make the UX better and avoid saving data which we would consider invalid.
The diff here is a bit large, but there shouldn't be anything too complex here, and …

MaintenanceWindow `requested_start` and `requested_end` validations

---

app/models/maintenance_window.rb
app/models/maintenance_window/validator.rb
db/data_migrations/20180223150748_update_existing_maintenance_windows.rb
spec/models/maintenance_window/validation_spec.rb
spec/models/maintenance_window_spec.rb

This PR fixes how we will migrate our existing production MaintenanceWindows to work, following recent changes to the MaintenanceWindow validations.
Based on #102.

Fix migrating existing MaintenanceWindows

---

spec/decorators/maintenance_window_decorator_spec.rb
spec/models/maintenance_window_spec.rb

Nothing major here, just:
- making things clearer/DRYer in `maintenance_window_spec`;
- improving test coverage in `maintenance_window_decorator_spec`.

MaintenanceWindow-related test tweaks

---

Gemfile
Gemfile.lock
app/controllers/maintenance_windows_controller.rb
app/decorators/maintenance_window_decorator.rb
app/models/maintenance_notifier.rb
app/models/maintenance_window.rb
app/models/maintenance_window/validator.rb
app/services/progress_maintenance_window.rb
db/data_migrations/20180223150748_update_existing_maintenance_windows.rb
db/migrate/20180323140700_add_duration_to_maintenance_windows.rb
db/schema.rb
spec/decorators/maintenance_window_decorator_spec.rb
spec/factories/maintenance_window.rb
spec/features/maintenance_windows_spec.rb
spec/models/component_group_spec.rb
spec/models/maintenance_window/validation_spec.rb
spec/models/maintenance_window_spec.rb
spec/services/progress_maintenance_window_spec.rb

This PR is the first step towards changing the time slot for a MaintenanceWindow from being specified as a `requested_start` and `requested_end` to being specified by a `requested_start` and a `duration` (in days). The maintenance should then last from `requested_start` until `duration` business days later, with only the former value being changeable by Site contacts when they confirm maintenance (so we always have the number of days we request to carry out maintenance).
This PR consists of most steps to remove/update our usage of `requested_end` and replace it with `duration` instead; updating the actual maintenance form to reflect this change is still to come.
Trello: https://trello.com/c/74FbrsaD/200-change-maintenance-form-to-show-requested-start-and-duration.

Add maintenance durations

---

app/controllers/maintenance_windows_controller.rb
app/decorators/application_decorator.rb
app/decorators/maintenance_window_decorator.rb
app/helpers/date_time_select_helper.rb
app/views/maintenance_windows/_form.html.erb
app/views/maintenance_windows/confirm.html.erb
app/views/maintenance_windows/new.html.erb
app/views/partials/_date_time_select.html.erb
config/environment.rb
db/migrate/20180323182505_remove_maintenance_window_requested_end.rb
db/schema.rb
spec/factories/maintenance_window.rb
spec/features/maintenance_windows_spec.rb

This PR completes https://trello.com/c/74FbrsaD/200-change-maintenance-form-to-show-requested-start-and-duration, by removing the `requested_end` field entirely and allowing setting maintenance `duration`s from the maintenance form.
Based on #136.

Allow specifying maintenance durations in form; remove requested_end

---

config/application.rb
spec/features/maintenance_windows_spec.rb
spec/models/maintenance_window_spec.rb
spec/services/progress_maintenance_window_spec.rb

Use our local time zone whenever we work with/display times in app; no matter where users are we want to use and for them to see the schedule that we operate on.
This change is necessary as previously we used UTC everywhere, which worked fine for us until daylight saving time started the other day, after which the times things would occur were an hour off from what we'd expect.
Still save everything in UTC; should make things more straightforward if we ever want to handle times in other time zones in future.
Also needed to update some failing tests following this change; these were fixed by using the `Time` rather than `DateTime` class, which I presume is dues to `DateTime` not handling daylight saving time (see https://stackoverflow.com/a/21075654/2620402).
Trello: …

Fix time handling

---

app/models/case.rb
app/views/logs/index.html.erb
app/views/maintenance_windows/_form.html.erb
spec/features/log_spec.rb
spec/features/maintenance_windows_spec.rb
spec/models/case_spec.rb

This PR filters the selectable Cases in the log and maintenance forms so only the active/non-archived Cases can be selected. To do this it adds an `active` scope to `Case` so we can also do this in other places in future.
Trello: https://trello.com/c/3E1HFmrM/170-hide-archived-cases-from-any-drop-down-when-asked-to-choose-tickets.
Related previous PR: https://github.com/alces-software/alces-flight-center/pull/146.

Filter Cases so only active selectable

---

app/models/case.rb
app/models/fake_request_tracker_interface.rb
db/migrate/20180405103917_add_completion_time_to_case.rb
db/schema.rb
docs/release-process.md
lib/tasks/cases.rake
lib/tasks/cron.rake
spec/features/cases_spec.rb
spec/lib/tasks/cases_spec.rb
spec/lib/tasks/cron_spec.rb

This PR adds the ability to automatically archive cases whose corresponding RT tickets have been completed at least two weeks ago.
An hourly rake cron task updates ticket statuses for all non-archived `Case`s.
If a ticket has transitioned from a non-completed state to a completed one (or fsr a resolution time wasn't previously recorded), the RT resolution time is recorded (if present - else current time is used) as the `Case`'s "completion time".
If the completion time is two weeks ago or greater, then the `archived` flag is also set on that `Case` and this change is logged to a file.
Trello: https://trello.com/c/OetM2i5j/169-auto-archive-cases-when-resolved-for-2-weeks

Automatically archive completed cases after two weeks

---

app/models/issue.rb
spec/models/issue_spec.rb

By default we want to support the creation of a Tier 3/consultancy Case, with the ability to provide any arbitrary details, for every Issue.
Trello: https://trello.com/c/l7nOOOeV/219-automatically-create-level-3-tier-for-each-issue-when-it-is-created-1-4-day.

Create automatic level 3 Tier for each new Issue

---

app/models/issue.rb
db/data_migrations/20180409163843_migrate_existing_data_to_account_for_tiers.rb

Sketch out the initial data migration to update all current Issues and Cases for the new relations to Tiers or Tier-related fields, respectively, that they will now need.
The exact details of the specific Tiers or the format of the Tier-related fields that we need may later change as we determine our requirements in more detail, or if we alter the data format needed for Tier fields; if this happens this migration can then be updated or an additional migration made as needed (depending on whether we have already deployed it).
Trello: https://trello.com/c/dxor1dSa/220-migrate-data-for-existing-issues-cases-for-tiers-1-2-day.

Migrate existing data for tiers

---

app/javascript/packs/Cluster.elm
app/javascript/packs/Field.elm
app/javascript/packs/Issue.elm
app/javascript/packs/Main.elm
app/javascript/packs/SelectList/Extra.elm
app/javascript/packs/State.elm
app/javascript/packs/Tier.elm
app/javascript/packs/View/Fields.elm
app/models/issue.rb
app/models/tier.rb
spec/factories.rb
spec/models/issue_spec.rb
spec/models/tier_spec.rb

This PR:
- encodes `Tier`s for use in the `Case` form, as an additional level under `Issue`s;
- decodes this encoded data into an appropriate structure in the `Case` form;
- displays a select box of the available `Tier`s for the currently selected `Issue`, with `Tier`s ordered by `level`;
- supports changing the selected `Tier` using this select box.
It does not actually do anything with the selected `Tier` (other than dump it into the page for debugging purposes); this is still to come in a future PR and for now the `Case` form otherwise functions as before.
Trello: https://trello.com/c/nG4gEcKr/222-update-case-form-to-render-tier-select-1-2-day.

Allow selecting tiers in Case form

---

db/data_migrations/20180409163843_migrate_existing_data_to_account_for_tiers.rb

This PR makes some tweaks to the initial Tiers generated for the existing Flight Center Issues, to:
- add a level 0/guides Tier, so can test out and demonstrate using this;
- tweak the various level 2 Tiers already generated for each Issue, to adjust some of their fields to be of a better `type` or have better wording.
No corresponding card for this, just a needed change to have things appear better in the Case form.

Improve initial generated Tiers

---

app/assets/stylesheets/cases.scss
app/javascript/packs/Field.elm
app/javascript/packs/Issue.elm
app/javascript/packs/Main.elm
app/javascript/packs/State.elm
app/javascript/packs/Tier.elm
app/javascript/packs/Types.elm
app/javascript/packs/Validation.elm
app/javascript/packs/View/Fields.elm
app/models/concerns/admin_config/issue.rb
app/models/issue.rb
db/data_migrations/20180409163843_migrate_existing_data_to_account_for_tiers.rb
db/migrate/20180412163928_make_issue_details_template_nullable.rb
db/schema.rb
elm-package.json
spec/factories/issue.rb
spec/models/issue_spec.rb

This PR removes the 'Details' field previously always shown in the Case form, and instead dynamically renders all `fields` appropriately for the currently selected Tier. When submitted the Case form then uses the entered values for these fields to form the `details` for the Case to be created (for now; later we will submit JSON for the fields themselves and handle this).
Trello: https://trello.com/c/S0TAsPRq/224-update-case-form-to-render-dynamic-tier-fields-2-days, with the validation part of this still to come.

Render dynamic Tier fields in Case form

---

app/controllers/case_comments_controller.rb
app/controllers/cases_controller.rb
app/models/case.rb
app/models/case_comment.rb
app/views/case_comments/_case_comment.html.erb
app/views/case_comments/_form.html.erb
app/views/cases/show.html.erb
config/routes.rb
db/migrate/20180406110011_create_case_comments.rb
db/schema.rb
spec/factories.rb
spec/models/case_comment_spec.rb

This PR adds the ability for users to add comments to cases.
A user may comment on any `Case` within their `Site`. Admins may comment on any `Case`. Comments are displayed from oldest to newest on a `Case`'s page, with the name of the user who posted the comment and the date and time at which they did so.
Empty comments are prohibited, and comments must be at least two characters long ("OK" probably being the tersest possible comment still containing useful information).
Trello: https://trello.com/c/JHENp9CD/217-add-comments-to-cases-2-days-moreish

Add comments to cases

---

app/javascript/packs/Main.elm
app/javascript/packs/Tier.elm

This PR prevents the creation of Tier 0 Cases in the Case form, since for Tier 0 we just want to show rendered markdown links to relevant documentation to try to help people solve issues without needing to create Cases.
Trello: https://trello.com/c/gS87kzAB/230-hide-submit-button-of-case-form-when-tier-0-selected-1-4-day.

Prevent creating Tier 0 cases

---

app/models/case/issue_validator.rb
spec/models/case/validation_spec.rb

In the particular situation where an attempt is made to create a Case
with:
- an `advice-only` Issue which requires a Component or Service;
- a `managed` Cluster;
- an `advice` Component or Service (as appropriate to match the Issue);
the Case would be invalid with the error that an advice-only Issue
cannot be created for a managed Cluster.
However, this is surprising and not what we want to happen, as just the
Component/Service's `support_type` should be considered in this
situation to determine if the Issue can be associated. This changed
behaviour is also consistent with what we already did when creating a
Case with a `managed` Issue which requires a part and an `advice`
Cluster.

Fix issue with creating Case for advice-only Issue

---

app/controllers/cases_controller.rb
app/decorators/case_decorator.rb
app/decorators/cluster_part_decorator.rb
app/javascript/packs/State.elm
app/javascript/packs/Tier.elm
app/models/case.rb
app/models/concerns/admin_config/case.rb
app/views/cases/show.html.erb
db/data_migrations/20180409163843_migrate_existing_data_to_account_for_tiers.rb
db/migrate/20180417164616_make_case_details_nullable.rb
db/schema.rb
spec/controllers/cases_controller_spec.rb
spec/decorators/case_decorator_spec.rb
spec/decorators/component_decorator_spec.rb
spec/decorators/service_decorator_spec.rb
spec/factories.rb
spec/factories/case.rb
spec/factories/issue.rb
spec/features/components_spec.rb
spec/features/log_spec.rb
spec/features/services_spec.rb
spec/models/case_spec.rb
spec/support/shared_examples/support_type_change_buttons.rb

This PR changes the Case form submission so the entered `fields`, as originally given by the selected Tier but with value entries also set, are submitted with the form as JSON rather than by forming a single `details` string as was previously done. These `fields` are then saved and can then be viewed on the Case page as a table of field names and values, rather than showing a single 'Details' section.
As part of doing this the buttons shown for Components and Services to request a change of support type also needed to be changed to submit the correct `fields` rather than `details`, and while doing this the test coverage of these was also improved.
Following this change the Case `details` column was then able to be made nullable and mostly be removed from being used in the app, and will be …

Handle Case Tier field submission

---

app/assets/stylesheets/cases.scss
app/javascript/packs/Field.elm
app/javascript/packs/Issue.elm
app/javascript/packs/State.elm
app/javascript/packs/SupportType.elm
app/javascript/packs/Validation.elm
app/javascript/packs/View/CaseForm.elm
app/javascript/packs/View/Fields.elm
app/javascript/packs/View/PartsField.elm

This PR changes the behaviour of the Case form so that when a Tier is unavailable for the currently selected Component, or Service if a Component is not required, then:
- the Tier is indicated as invalid with a relevant error message;
- submitting the form is correspondingly disabled;
- all inputs in the lower section of the form are disabled, and this section is faded out with title text indicating why this is the case.
Trello: https://trello.com/c/V3JLLsLh/235-disable-tier-0-2-support-for-self-managed-clusters-services-components-1-2-day

Disable non consultancy support for self managed things

---

app/javascript/packs/Issue.elm
app/javascript/packs/Msg.elm
app/javascript/packs/State.elm
app/javascript/packs/State/Update.elm
app/javascript/packs/State/View.elm
app/javascript/packs/Tier.elm
app/javascript/packs/View/CaseForm.elm
app/javascript/packs/View/Charging.elm
app/models/case.rb

This PR switches the Case form from displaying
- the chargeable alert, with link to Cluster charging info modal;
- the chargeable warning modal on submit of a potentially chargeable Case;
to be based on the `level` of the selected Tier rather than the `chargeable` value of the selected Issue. Currently level 3 Tiers are always chargeable and other Tiers are never chargeable.  
Trello: https://trello.com/c/HKj8Qi7t/238-indicate-on-case-form-that-tier-3-support-is-potentially-chargeable-1-2-day

Show Tier charging info

---

app/javascript/packs/Category.elm
app/javascript/packs/Field.elm
app/javascript/packs/Msg.elm
app/javascript/packs/State.elm
app/javascript/packs/State/View.elm
app/javascript/packs/Tier.elm
app/javascript/packs/Tier/Field.elm
app/javascript/packs/Validation.elm
app/javascript/packs/View/CaseForm.elm
app/javascript/packs/View/Charging.elm
app/javascript/packs/View/Fields.elm
db/data_migrations/20180409163843_migrate_existing_data_to_account_for_tiers.rb
elm-package.json

This PR adds client-side validation that Tier fields are filled, where this is required. Currently this consists of:
- unless marked as `optional`, Tier fields with inputs are validated to check they have some non-whitespace text entered;
- if they are marked `optional`, this is now indicated using a badge alongside the field; a single example field marked as `optional` has also been added to the data migration to demonstrate this (to the 'From available Alces Gridware' Issue);
- these validations are run (so the form cannot be submitted) but are not shown for each field until it has been touched, to avoid overwhelming a user with many fields most of which are initially invalid.
Trello: https://trello.com/c/DkP7YQWz/241-validate-in-case-form-that-tier-fields-have-non-empty-values-unless-th …

Validate Tier fields client-side

---

app/decorators/case_decorator.rb
app/models/case.rb
app/models/case/available_support_validator.rb
app/views/case_comments/_form.html.erb
spec/features/cases_spec.rb
spec/models/case_spec.rb

This PR disables commenting on Cases for Site contacts when the Case is not consultancy (with our business reasoning for doing this being that theoretically the original Case should contain all relevant information in this situation). 
@jamesremuscat would you be able to take a quick look at this, since this touches the stuff you've been working on? :slightly_smiling_face: 
Trello: https://trello.com/c/Wqcy44Py/233-disable-case-commenting-with-standard-reason-displayed-for-tier-1-2-cases-1-4-day

Disable non-consultancy Case comments

---

app/mailer_previews/case_mailer_preview.rb
app/models/case.rb
app/views/case_mailer/new_case.html.erb
app/views/case_mailer/new_case.text.erb
app/views/cases/show.html.erb
spec/controllers/cases_controller_spec.rb
spec/factories.rb
spec/mailers/case_mailer_spec.rb
spec/models/case_spec.rb

This PR updates the new Case emails so they include the new Tier fields, appropriately formatted for the medium (text vs HTML); this replaces showing the Case details, which are no longer set for new Cases and will eventually be removed. @jamesremuscat you may want to look at this as this touches stuff you've been working on :slightly_smiling_face:.
A few related changes were also made along with this:
- making it possible to preview the new Case emails for different Cases in the email preview pages, by adding a `case_id` parameter to the URL;
- tweaking the other fields shown in the emails (showing the Tier level and accompanying description, and removing the requestor which is now already shown);
- removing the charging-related fields from the Case page, as these have become …

Show tier fields in new Case emails

---

app/controllers/application_controller.rb
app/helpers/application_helper.rb
app/helpers/scope_nav_links_builder.rb
app/views/cases/show.html.erb
app/views/partials/_nav_bar.html.erb
spec/features/nav_bar_spec.rb

This PR:
- makes the drill-down menu be shown when on an individual Case page;
- also makes the tabs for the corresponding dashboard (i.e. for the last entry in the drill-down) be shown when on this page, for consistency and to give the user routes to related actions;
- refactors generating this drill-down to make this a bit simpler to change in future.
Also related: https://trello.com/c/bj7KZixd/256-show-all-correct-links-in-header-of-case-page.

Fix navbar drill-down and tabs on Case page (fixes #188)

---

app/controllers/cases_controller.rb
app/helpers/tabs_helper.rb
app/models/case.rb
app/views/cases/_case_state_controls.html.erb
app/views/cases/index.html.erb
config/routes.rb
db/data_migrations/20180501133322_rename_archived_to_closed.rb
spec/controllers/cases_controller_spec.rb
spec/factories/case.rb
spec/features/cases_spec.rb
spec/features/log_spec.rb
spec/features/maintenance_windows_spec.rb
spec/models/case_spec.rb

This PR makes some changes to the (formerly) "Archived cases" page:
- Page is renamed to "Resolved cases", routed from `.../resolved`
- Final Case state is renamed from `archived` to `closed`
- "Resolved cases" page no longer shows open cases, only `resolved` and `closed` ones
Note that I've included a new data migration to convert all cases with `archived` state to `closed`, although I'm not sure that it will apply to anything at the moment!
This closes #206.

"Archived case" page cleanup

---

app/views/case_comments/_form.html.erb

As title.
Trello: https://trello.com/c/oSqqaXvS/250-make-it-more-obvious-why-non-consultancy-cases-cannot-be-commented-on
Fixes #202.

Make "no comments allowed" message more visible

---

app/controllers/cases_controller.rb
app/decorators/application_decorator.rb
app/decorators/case_decorator.rb
app/mailers/case_mailer.rb
app/models/case.rb
app/models/log.rb
app/views/cases/show.html.erb
app/views/logs/index.html.erb
spec/decorators/application_decorator_spec.rb
spec/decorators/case_decorator_spec.rb
spec/features/cases_spec.rb
spec/features/log_spec.rb
spec/models/case_spec.rb
spec/models/log_spec.rb

As just discussed IRL these are the changes to be more consistent and correct with how we refer to cases. Essentially this makes it so:
- we always refer to Cases when we mean Flight Center Cases, rather than tickets, and only refer to tickets when we actually mean an RT ticket;
- we use the `display_id` method wherever we previously showed the RT ticket ID (except where we need to keep our previous behaviour for a reason, such as in emails to avoid breaking threading with previous emails);
- `display_id` has been moved to `Case` since it fits better there now;
- the comments in https://github.com/alces-software/alces-flight-center/commit/5402a790f415a474ceb63ca568b0fd539b1240ab may be relevant to you @jamesremuscat for your current work on …

Remove last unnecessary ticket and ticket_id references

---

app/controllers/application_controller.rb
app/controllers/case_comments_controller.rb
app/controllers/cases_controller.rb
app/models/case.rb
app/models/cluster.rb
app/views/cases/index.html.erb
db/data_migrations/20180502100018_set_cluster_shortcodes.rb
db/data_migrations/20180502110608_set_case_display_ids.rb
db/migrate/20180502093509_add_shortcode_and_case_index_to_cluster.rb
db/migrate/20180502104232_add_display_id_to_cases.rb
db/schema.rb
spec/controllers/cases_controller_spec.rb
spec/decorators/case_decorator_spec.rb
spec/factories/cluster.rb
spec/models/case_spec.rb
spec/models/cluster_spec.rb

This PR changes the way we publicly refer to `Case`s by introducing a per-cluster sequential "display ID", prefixed with a new "shortcode" allocated to each cluster.
The `#display_id` method on `Case` is therefore replaced by simply accessing the value of this stored field.
New-style display IDs are of the form `BAR123` - this being the 123rd case raised for the `BAR` cluster (which, in production, would be the shortcode allocated to Barkla).
Old cases with RT ticket IDs use a display ID of the form `RT12345`, as previously.
Display IDs are allocated immediately before the initial save of a `Case` (specifically, using the `before_create` callback). It is from `Cluster` that the numeric part of the display ID is obtained, and we use a database row-level lock on the cluster to ensure …

Generate per-cluster sequential case IDs

---

app/controllers/cases_controller.rb
app/javascript/packs/Tier/Field.elm
app/javascript/packs/View/CaseForm.elm
app/javascript/packs/View/Fields.elm
app/javascript/packs/View/Utils.elm
db/data_migrations/20180504104059_add_some_example_help_to_fields.rb

This PR allows specifying `help` text within the Tier fields JSON, and having this then be displayed in the Case form alongside the field. This is done by refactoring and then adding this functionality, in such a way that it should be slightly easier to add similar additional fields with special handling to the Tier fields JSON next time.
This closes #211 and completes https://trello.com/c/2RkPP0zI/270-add-ability-to-add-hints-for-inputs-in-tiers-in-case-form.

Support help text for Tier fields

---

app/decorators/component_decorator.rb
app/views/logs/index.html.erb
spec/features/log_spec.rb

A new column has been added to the log page to display a link to the `Associated Component` of a log where one exists. If there is no component assigned to a log then it will simply display '_None_'
This PR fixes #185.

Display associated component for a log

---

app/decorators/cluster_decorator.rb
app/decorators/component_decorator.rb
app/helpers/tabs_helper.rb

Much like on the `Cluster` dashboard there is now a `Logs` tab on the `Component` dashboard. This allows you to view all logs for that component from within its dashboard.
This is based off #228

Display logs tab on the component dashboard

---

.travis.yml

As of today we need to opt-in to using apt-get install as Travis has changed the build script to not run apt-get update by default. This may change in the future but this is their fix for the time being.

Add flag to opt-in to using apt-get install

---

app/models/case.rb
app/models/change_motd_request.rb
app/models/change_motd_request_state_transition.rb
app/models/cluster.rb
app/models/tier.rb
db/data_migrations/20180509095726_add_placeholder_motds.rb
db/data_migrations/20180509115018_add_change_motd_issue.rb
db/migrate/20180508171035_create_change_motd_requests.rb
db/migrate/20180508173313_data_model_changes_for_tier1_tools.rb
db/migrate/20180509144921_create_change_motd_request_state_transitions.rb
db/schema.rb
spec/factories.rb
spec/factories/cluster.rb
spec/models/case_spec.rb
spec/models/change_motd_request_spec.rb
spec/models/change_motd_request_state_transition_spec.rb
spec/models/cluster_spec.rb
spec/models/tier_spec.rb

This PR makes various data model updates, and some actual data changes alongside these, to set things up for implementing the Tier 1 tools, in particular the MOTD update tool - see https://trello.com/c/ECGJfu3D/282-update-data-model-for-motd-and-future-tier-1-tools for full details. Going to leave this open but un-merged until I've implemented the next step since the Case form has not yet been updated to decode the new data format.

Update data model for tier 1 tools

---

lib/deployment.rb

Fix needed when doing the latest staging deploy; don't know why this wasn't previously an issue but this appears to fix it.

Get Dokku config values without trailing whitespace

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/cases.scss
app/views/cases/show.html.erb

Previously cases with very little added to fields would have the table pushed to the far right of the given space. With these changes the table header now shrinks to the longest field available, giving more space to actual data and improving readability.
_(Trello: https://trello.com/c/5KrWmFS9/279-fields-table-can-show-squashed-up-with-lots-of-space-for-keys-and-not-much-for-values-when-not-much-text-entered-for-values)_

Give more room to table data

---

app/helpers/application_helper.rb

In three of the four ways that `clusters` can be set, it's set to an array (a singleton, as it happens). Only in the fourth case is it set to an `ActiveRecord::Associations::CollectionProxy` with a `decorate` method, and that was the only case in which the new case form was working (when accessed from a site dashboard).
This commit fixes the form to work for the other code paths by assuming `clusters` is an array, and calling `decorate` on each of its members directly.
Fixes #254.

Fix new case form in non-site-wide uses

---

app/assets/stylesheets/cases.scss
app/controllers/logs_controller.rb
app/models/case.rb
app/models/log.rb
app/models/maintenance_window.rb
app/views/cases/index.html.erb
app/views/maintenance_windows/_form.html.erb
app/views/partials/_case_table_row.html.erb
spec/features/cases_spec.rb

This PR implements prioritisation and highlighting of cases that have been assigned to the current user. Cases are split into two distinct groups of those that are and aren't assigned to the current user. With those that are assigned appearing first and foremost at the top in descending order with a darker background to make them stand out.
_(Trello: https://trello.com/c/rvMjwwcA/287-make-cases-assigned-to-current-user-more-prominent-every-time-we-display-case-tables)_

Prioritise cases assigned to the current user

---

app/controllers/application_controller.rb
app/controllers/cases_controller.rb
app/controllers/sites_controller.rb
app/decorators/all_sites_decorator.rb
app/helpers/scope_nav_links_builder.rb
app/models/all_sites.rb
app/views/sites/index.html.erb
spec/decorators/all_sites_decorator_spec.rb
spec/requests/navigation_variable_assignments_spec.rb

The admin dashboard now contains tabs to switch between viewing `All sites` and `All cases`. The former displays what admins currently see on the dashboard. Whereas the latter will display **all** open cases, with the option to view all resolved/closed cases via the dropdown.
Once #247 has been merged then this page should also filter by cases assigned to the current user.
[Trello Card](https://trello.com/c/4V06Dvme/269-add-case-management-pages-for-admins)

Admin case management page

---

app/controllers/cases_controller.rb
app/decorators/audited/audit_decorator.rb
app/decorators/case_decorator.rb
app/helpers/application_helper.rb
app/mailers/application_mailer.rb
app/models/case.rb
app/views/cases/_escalation_controls.html.erb
app/views/cases/show.html.erb
config/routes.rb
spec/controllers/cases_controller_spec.rb
spec/features/cases_spec.rb

This PR adds the ability for users - both contacts and admins - to escalate an open case up to tier 3.
When viewing an open tier 2 case, there is now a button next to the "Tier" value marked "Escalate". Clicking this button will open a modal almost identical to the one used in the new-case form warning that: 
> Escalating a support case means that the case becomes potentially chargeable, and may incur a charge of support credits.
If the user proceeds, then the case is set to tier 3 and an entry logged in the case history feed.
This is a one-time, irreversible action - once done a case cannot be de-escalated (though whether or not a case actually incurs a credit charge is a separate, if related, concern). It is not possible to escalate resolved or closed tickets.
Trello: …

Case escalation

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/sites.scss
app/decorators/site_decorator.rb
app/decorators/user_decorator.rb
app/models/site.rb
app/models/user.rb
app/views/layouts/application.html.erb
app/views/sessions/new.html.erb
app/views/sites/show.html.erb
spec/decorators/user_decorator_spec.rb
spec/models/site_spec.rb
spec/models/user_spec.rb

This PR makes some changes to the site dashboard to improve the user experience.
Primarily, it makes more prominent links to each cluster's management dashboard and cases, taking the focus away from the (now renamed) "all site cases" page that was formerly the most obvious.
Site contacts are now listed with clickable email addresses rather than unclickable ones.
I've also taken the opportunity to kill off the Jumbotron page header, replacing it with something a little more compact so that content has a chance of making it "above the fold"; and made some tweaks to the base page layout to reduce the number of empty columns we were rendering.
Trello: https://trello.com/c/bvriA3hT/289-make-site-dashboard-ui-more-intuitive

Improve site dashboard UI/UX

---

app/controllers/cases_controller.rb
app/helpers/application_helper.rb
app/javascript/packs/State.elm
app/javascript/packs/Tier.elm
app/javascript/packs/View/Charging.elm
app/mailer_previews/case_mailer_preview.rb
app/models/case.rb
app/views/case_mailer/new_case.html.erb
app/views/cases/show.html.erb
config/initializers/vcr.rb
spec/factories.rb
spec/features/case_form_spec.rb
spec/features/cases_spec.rb
spec/helpers/application_helper_spec.rb
spec/models/case_spec.rb

This PR implements handling of submission from the MOTD tool within the Case form app; in brief this involves:
- appropriately encoding the data for this within the Case form app;
- decoding and handling this data appropriately within Rails, to create a `ChangeMotdRequest` along with the new `Case`;
- handling displaying of these Cases appropriately within both emails and the Case table on the Case page.
This has all been done in such a way that it should be comparatively straightforward to slot handling for future Tier 1 tools into this process. 
Trello: https://trello.com/c/7b2HzqKz/284-handle-submission-of-motd-tool-appropriately.

MOTD tool submission

---

app/assets/stylesheets/application.scss
app/helpers/application_helper.rb
app/views/cases/index.html.erb
app/views/cases/show.html.erb
app/views/logs/index.html.erb
app/views/partials/_case_table_row.html.erb

This PR forces the table headers on `Case` pages to display on a single line. Previously they would wrap to a new line to display the second word of `Assigned to` and `Credit usage`. This had the effect of pushing the table content down slightly and as the headers are not massively long seemed unnecessary.
[Trello](https://trello.com/c/8aPaLSua/301-display-table-headers-on-a-single-line)

Display table headers on a single line

---

app/controllers/maintenance_windows_controller.rb
app/decorators/case_decorator.rb
app/views/cases/show.html.erb
app/views/maintenance_windows/_form.html.erb
spec/features/cases_spec.rb
spec/features/maintenance_windows_spec.rb

This PR makes some low-hanging-fruit changes to requesting maintenance windows (MWs) (relating to #233).
- Cases now have a button linking directly to a MW request form for the component/service/cluster associated with that case, and with the appropriate case pre-selected.
- The MW form now tells you what you're about to request maintenance for
- The MW form has a big orange warning if you try and request maintenance for an entire cluster, and suggests that you might want a service or component instead
Trello: https://trello.com/c/XIf3w3zB/290-make-maintenance-request-process-more-intuitive

Maintenance window request UI enhancements

---

app/mailers/application_mailer.rb
config/application.rb
lib/tasks/deploy.rake
spec/lib/tasks/deploy_spec.rb

This PR makes a couple of small email-related changes:
- The anonymisation process for deploying staging now changes contact email addresses to `center+$username@alces-software.com`, where `$username` is the contact `User`'s `name` with spaces removed.
- Emails sent from staging can now be distinguished from those sent by production, by setting the `EMAIL_APP_NAME` environment variable to something distinct e.g. `(Staging) Alces Flight Center` in staging.
Trello: https://trello.com/c/nYyOlva8/295-staging-email-tweaks

Staging email changes

---

app/decorators/all_sites_decorator.rb
app/helpers/tabs_helper.rb
app/models/case.rb
app/views/cases/index.html.erb
app/views/partials/_case_table_row.html.erb
app/views/sites/index.html.erb

This PR implements showing the total number of cases for a page in various places. On the page itself it will state how many cases there are in the format `# <case_state> Cases` e.g. `13 Open Cases`. 
However in the `Cases` dropdown menu a number will also be displayed in brackets next to `Current`. This is only done for `Current` and not `Resolved` as the number of resolved/closed cases will be racking up ad finem so displaying this within the dropdown seems unnecessary and unhelpful. 
Whereas showing the total number of open cases within the dropdown is potentially useful for seeing if there are any, and how many, open cases available. But it is still nice to have a record of the total number of resolved/closes cases within the subtitle of the page itself. …

Display the number of cases in dropdown and subtitle

---

app/decorators/case_decorator.rb
app/views/case_comments/_form.html.erb
spec/features/cases_spec.rb

Previously, a resolved or closed tier-2 case would erroneously display a "you can't comment because it's tier 2" message to contacts.
Now, a resolved or closed case of any tier displays a "you can't comment because it's resolved" (or closed) message to all users, and only open tier-2 cases display the former message (still only to contacts).
Trello: https://trello.com/c/kEw2MVZ3/294-should-we-still-show-the-additional-discussion-unavailable-box-for-tier-1-2-cases-when-the-case-is-not-open-and-so-additional-di

Show a more accurate message disabling commenting on non-open cases.

---

app/javascript/packs/View/Charging.elm

Display new default charging info provided by Steve at
https://alces.slack.com/archives/C72GT476Y/p1526552123000289.
Also support rendering Cluster charging info as markdown as a side
effect of rendering this from markdown (which is done as this doesn't
really matter for performance and since we may soon want to extract this
to not be embedded within the Case form app code, if we find we
semi-regularly want to update it).
Trello: https://trello.com/c/xOrQgQ28/243-set-useful-charginginfo-for-hamilton-and-barkla

Display new default charging info from Steve

---

app/controllers/clusters_controller.rb
app/decorators/cluster_decorator.rb
app/views/clusters/documents.html.erb
config/routes.rb
spec/features/cluster_tabs_spec.rb
spec/features/maintenance_windows_spec.rb
spec/features/nav_bar_spec.rb
spec/models/cluster_spec.rb
spec/rails_helper.rb
spec/requests/navigation_variable_assignments_spec.rb
spec/spec_helper.rb
spec/support/shared_examples/support_type_change_buttons.rb

This PR moves the "Documents" section on the cluster dashboard to its own tab, which is only shown if there are documents present.
Testing for this was a little tricky, so I've had to add 
```ruby
allow_any_instance_of(Cluster).to receive(:documents).and_return([])
```
into the RSpec config in `spec_helper.rb`, overriding it manually in the existing VCR-based test for S3 document retrieval.
For manual testing, I've also dropped a file in S3 for the demo cluster. It's not a long read.
Trello: https://trello.com/c/xomUxdm6/300-move-cluster-documents-into-a-tab

Move cluster documents to their own tab

---

app/views/cases/index.html.erb

Based off #273 so merge that first ideally.
This is a simple fix that ensures the subtitle is pluralised correctly. I noticed this was a problem when viewing a case page containing only a single case.
[Trello](https://trello.com/c/K7I7g3gw/95-indicate-number-of-cases-in-various-cases-tables)

Pluralise the cases subtitle correctly

---

app/decorators/case_decorator.rb
app/decorators/issue_decorator.rb
app/models/case.rb
app/models/issue.rb
db/data_migrations/20180509115018_add_change_motd_issue.rb
db/migrate/20180521104319_remove_obsolete_columns.rb
db/migrate/20180521142349_remove_chargeable_from_issues.rb
db/schema.rb
spec/decorators/issue_decorator_spec.rb
spec/factories/issue.rb

This PR removes some database columns that have become obsolete:
- `Case.details`
- `Issue.details_template`
- `Issue.support_type`
Trello: https://trello.com/c/YrsAysHk/226-remove-no-longer-needed-columns

Remove obsolete columns from a couple of places

---

app/mailers/application_mailer.rb
config/application.rb
config/environments/development.rb
config/environments/production.rb
lib/tasks/deploy.rake
spec/lib/tasks/deploy_spec.rb

This PR makes some changes to our email settings for staging, as prompted by @mjtko's requests in https://trello.com/c/Ej03zix1/321-in-staging-send-emails-from-centerstagingalces-softwarecom. Specifically we now:
- prevent sending emails in development;
- send emails from `center+staging@alces-software.com` in staging, so these can be more easily filtered;
- use a `STAGING` environment variable to toggle all staging vs production settings, so this is explicit in the code rather than configured in various places by the environment;
- fixed the obfuscating of contact emails to the form `center+...@alces-software.com`, so this doesn't blow up when run in staging.
I don't think there's anything too crazy here, and this is running seemingly successfully in staging atm, but @jamesremuscat would …

Email tweaks

---

app/models/case.rb
app/models/maintenance_window/validator.rb
db/migrate/20180521143035_add_needed_null_constraints.rb
db/schema.rb

This PR uses the `bin/generate-needed-null-constraint-migrations` script to add in a few more null constraints that weren't previously present.
I've also taken the opportunity to reenable the validation on `Case.display_id` that was disabled in 99f85c7e41bf97567fca6ea8ceeb8a4c3f57fa50
I've confirmed that `alces:data:import_and_migrate_production` completes successfully.
Note that there was also a small change to `maintenance_window/validator.rb` as `nullalign` was falling over the otherwise inconsistent type hierarchy.
Trello: https://trello.com/c/gtl57vpG/264-run-bin-generate-needed-null-constraint-migrations-and-add-any-constraints-we-can-now-add-after-running-migrations-in-production

Update null constraints and validation

---

app/models/user.rb
spec/models/user_spec.rb

Sites are only meant to have one `Primary Contact` assigned to them however there was no validation to prevent multiple contacts being assigned as the `Primary Contact`. This PR resolves this issue, ensuring that there can be only one. If an admin attempts to assign a user as the `Primary Contact` of a site that already has one then it will raise an error within the admin interface preventing the user from being saved.
[Trello](https://trello.com/c/NQZqLwPF/110-add-validation-that-site-only-has-single-primary-contact)

Primary contact validation

---

app/models/cluster.rb
app/models/component.rb
app/models/service.rb
spec/models/cluster_spec.rb

This PR validates `Services` in the same manner that `Components` are validated for advice based clusters.
[Trello](https://trello.com/c/AK9Truy4/120-missing-corresponding-validation-that-advice-cluster-does-not-have-managed-services-as-for-components)

Validate services for advice based clusters

---

app/views/cases/index.html.erb
app/views/logs/index.html.erb
app/views/maintenance_windows/index.html.erb
app/views/partials/_no_item_available.html.erb
app/views/partials/_table.html.erb

This PR doesn't implement anything too fancy but does handle if there are no cases, logs or maintenance to display. In the future this could be adapted to look nicer however for now it does what it needs to. It displays a short message indicating there are no items for the appropriate page to display and prevents the table headers from unnecessarily rendering.
[Trello](https://trello.com/c/W4VOTlw5/46-go-through-and-nicely-handle-when-no-items-available-in-various-cases)

Handle when no items available

---

app/decorators/log_decorator.rb
app/models/case.rb
spec/features/case/show_spec.rb

This PR adds log entries related to a `Case` to its events feed.
See https://trello.com/c/UhTEqeIH/179-should-we-support-markdown-rendering-for-log-entries-and-comments for a question on how these are rendered; for now we just use plain text, as in other places.
Trello: https://trello.com/c/wjZ6C9tM/317-associated-log-entries-should-appear-in-case-history
Fixes #234.

Display log entries in case history

---

app/views/sites/show.html.erb

They don't render properly in browsers on OSX.
As far as I'm aware, *buttons* with `@type='button'` render perfectly well (we use those in many places), it's just `a` tags that don't (and we only used those here).
Trello: https://trello.com/c/A0x2GYm4/322-remove-typebutton-from-buttony-anchors

Remove `@type='button'` from these link buttons.

---

config/application.rb

As title.
Trello: https://trello.com/c/h9YdNOD3/324-correct-emails-displayed-by-flight-center-to-be-alces-flightcom

Change `From:` addresses to `alces-flight.com` domain.

---

lib/tasks/data.rake

When running `rake alces:data:import_and_migrate_production`, if running
the `bin/import-production-data` script failed (which could happen for
many reasons - lack of AWS keys being available, network error etc.) we
would previously blindly carry on. This would then cause an odd error to
occur as the Rake task would then attempt to run all the regular and
data migrations over an empty database, which doesn't work (normally it
should run just the migrations since we last deployed to production over
the imported production database).
This commit fixes this by aborting the task in this case, so you can
then easily see the real reason that things failed.
^ @atoghill this should make it more obvious what went wrong next time you get that issue.

Fix production data import error being obscured

---

db/schema.rb

Apparently Rails 5.2 changed the schema version format, so let it update
this as it wants.

Let Rails 5.2 update schema version

---

Gemfile
Gemfile.lock
config/initializers/resque-sentry.rb

Thanks @jamesremuscat for pointing me towards this:
https://github.com/alces-software/alces-flight-center/issues/257#issuecomment-390653217.
Trello: https://trello.com/c/pLfaiKEn/304-sentry-not-reporting-errors-from-non-web-containers

Send resque errors to Sentry with resque-sentry (fixes #257)

---

app/views/sites/show.html.erb

They don't render properly in browsers on OSX.
Backport of #298.

Remove `@type='button'` from these link buttons. [backport of #298]

---

Gemfile
Gemfile.lock
config/initializers/resque-sentry.rb

Thanks @jamesremuscat for pointing me towards this:
https://github.com/alces-software/alces-flight-center/issues/257#issuecomment-390653217.
Backport of #310.

Send resque errors to Sentry with resque-sentry (fixes #257) [backport of #310]

---

app/models/case.rb
app/models/site.rb
app/models/user.rb
app/views/cases/_case_assignment_controls.html.erb
db/data/20180525164417_set_user_roles.rb
db/data_schema.rb
db/migrate/20180525161250_add_role_to_users.rb
db/migrate/20180525175459_replace_old_user_type_fields.rb
db/schema.rb
lib/tasks/deploy.rake
spec/factories/user.rb
spec/models/case_spec.rb
spec/models/user_spec.rb

This PR switches Flight Center to using a `role` field to distinguish different types of Users with different abilities, of which there are currently 4 - `admin`, `primary_contact`, `secondary_contact`, and `viewer` (a new type of User, with special handling still to come).
Trello: https://trello.com/c/vezaEjgb/338-update-data-model-with-user-roles. This is the first step towards implementing https://github.com/alces-software/alces-flight-center/issues/301.

Switch to user roles

---

app.json
deploy/post-deploy
lib/deployment.rb

Rather than by running another Rake task on the container after the
deploy. From a brief test in staging this appears to work, and should
have the advantages of:
- hopefully preventing an issue we've seen occur a couple of times,
where the app can be deployed but seemingly using old knowledge of the
database, leading to odd errors until it is restarted (see
https://trello.com/c/EXlN6VuQ/323-investigate-why-new-code-didnt-entirely-appear-to-be-running-after-deploy);
- meaning we don't have a brief period when the app is running but the
database has not been (fully) migrated, which could potentially cause
various odd issues in this period regardless of if the above occurs.
Following this change we also need to update when we import the staging
database to also run migrations, since this …

Migrate database in post-deploy hook [skip ci]

---

app/controllers/application_controller.rb
app/controllers/case_comments_controller.rb
app/controllers/cases_controller.rb
app/decorators/all_sites_decorator.rb
app/decorators/application_decorator.rb
app/decorators/case_decorator.rb
app/views/cases/index.html.erb
app/views/partials/_case_table_row.html.erb
config/routes.rb
spec/decorators/case_decorator_spec.rb
spec/features/case/show_spec.rb
spec/features/nav_bar_spec.rb

This PR implements the ability to view cases from within the same dashboard you were previously in. Meaning you will no longer be unexpectedly moved to a different dashboard after clicking a link to view a specific case that may be relating to a different context than your current dashboard.
[Trello](https://trello.com/c/BtXmytRu/326-need-multiple-pages-for-a-case-for-each-level-it-is-available-for)

Keep the user in the same dashboard when viewing a case

---

app/mailers/application_mailer.rb
spec/decorators/application_decorator_spec.rb
spec/decorators/case_decorator_spec.rb
spec/decorators/maintenance_window_decorator_spec.rb

Rather than needing to do this all over the place whenever/wherever we
notice the issue; since the issue is caused by rendering emails and
Draper getting confused, we can just do this after emails are rendered,
which appears to fix the problem in every case (and probably future
cases too).

Fix Draper ViewContext issue once

---

app/controllers/case_comments_controller.rb
app/controllers/cases_controller.rb
app/decorators/all_sites_decorator.rb
app/decorators/application_decorator.rb
app/models/all_sites.rb
app/models/application_record.rb
app/views/partials/_case_table_row.html.erb
spec/features/case/show_spec.rb

The problem that #328 fixes relates to changes made in this PR. It became apparent that handling the case paths for the various dashboards in their `Decorator` was problematic because of the problem described in #328.
Therefore this PR extracts `dashboard_case_path` to the relevant models, removing itself from the issue of `Draper` context switching. On top of this a test has been added to check the assignment button on a `Case` works. This was previously not being tested and would have picked up on the issue sooner.

Extract path logic from decorators

---

.env.example
Gemfile
Gemfile.lock
README.md
app/controllers/logs_controller.rb
app/mailers/case_mailer.rb
app/models/case.rb
app/models/slack_notifier.rb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
config/initializers/routes.rb
config/secrets.yml
spec/features/log/index_spec.rb
spec/features/maintenance_windows_spec.rb
spec/mailers/case_mailer_spec.rb
spec/spec_helper.rb

Introduced in this PR is the Slack integration for `Alces Flight Center`. This notifier is intended to send notifications to the support channel of our Slack workspace whenever an email would normally be sent, or a new log is created. For a full list of notification events see towards the bottom of this PR.
There are a few environment variables associated with this integration, the WebHook URL, channel and username. The former is vital for sending notifications whereas the latter can be used for mostly development purposes.
Within your `.env` file you will need to set the `SLACK_WEBHOOK_URL` to match the value found within the `Alces Flight Center` Incoming WebHook on Slack. Without this the application will not be able to send the notifications to Slack but should only silently fail if …

Slack Notifier

---

app/controllers/case_comments_controller.rb
app/controllers/cases_controller.rb
app/controllers/component_expansions_controller.rb
app/decorators/case_decorator.rb
app/models/case_comment.rb
app/models/case_commenting.rb
app/models/concerns/admin_config/user.rb
spec/models/case_commenting_spec.rb
spec/models/user_spec.rb

This PR adds various changes made following the switch to distinguishing types of Users by `role`, and prior to adding full authorisation based on `role`s, using [Pundit](https://github.com/varvet/pundit). This largely consists of various refactoring, adding some tests, and an admin interface tweak - see commits for details, and the reasons for making these changes should become clear in the subsequent PRs (submitting these changes on their own here for clarity, to keep them distinct from the actual behaviour changes to come in the next PRs).

Misc post-roles/pre-authorization changes

---

app/models/case.rb
app/models/case_commenting.rb
app/models/user.rb
app/views/partials/_nav_bar.html.erb
spec/factories/user.rb
spec/models/case_commenting_spec.rb
spec/models/case_spec.rb
spec/models/user_spec.rb

This PR makes various tweaks following the addition of `viewer` Users, such as accounting for `viewer`s in a couple of places where we previously only considered contacts and admins, and indicating what the current User's `role` is in the app nav bar - see commits for full details. This is a step towards implementing https://trello.com/c/JvjCbEAh/339-prevent-viewers-from-interacting-with-things.

Minor role tweaks

---

app/policies/maintenance_window_policy.rb
spec/policies/maintenance_window_policy_spec.rb

This was previously allowed at the model level, but I hadn't accounted
for admins also being able to confirm maintenance when implementing this
policy. This commit corrects this so both admins and contacts can
confirm maintenance.

Allow access to confirm MWs for admins

---

app/controllers/application_controller.rb
app/controllers/root_controller.rb
config/initializers/rails_admin.rb

Following the introduction of app-wide authorisation using Pundit (done
in #338), the
RailsAdmin routes had accidentally become inaccessible as we now verify
most controller actions perform an authorisation check, and RailsAdmin
actions were not doing this.
A straightforward solution to this, since we want authorisation enforced
within our app but not in RailsAdmin, is to have one RootController
which will be inherited from both by the ApplicationController and by
other engines, while any app-specific behaviour can just be in the
ApplicationController which RailsAdmin controllers no longer inherit
from.

Fix auth failure when accessing RailsAdmin routes

---

Gemfile
Gemfile.lock
app/decorators/site_decorator.rb
app/models/site.rb
app/models/user.rb
app/views/sites/show.html.erb
spec/decorators/site_decorator_spec.rb
spec/models/site_spec.rb
spec/spec_helper.rb

This PR makes Site viewers be displayed on the Site dashboard overview page, in a similar way to the secondary contacts, along with some related refactoring and addition of tests.

Display site viewers

---

app/controllers/notes_controller.rb
app/decorators/cluster_decorator.rb
app/decorators/note_decorator.rb
app/models/cluster.rb
app/models/concerns/admin_config/note.rb
app/models/note.rb
app/policies/note_policy.rb
app/views/notes/_form.html.erb
app/views/notes/edit.html.erb
app/views/notes/new.html.erb
app/views/notes/show.html.erb
config/routes.rb
db/migrate/20180605135005_create_notes.rb
db/schema.rb
lib/tasks/data.rake
spec/factories/note.rb
spec/features/cluster_tabs_spec.rb
spec/models/note_spec.rb
spec/policies/note_policy_spec.rb
spec/requests/notes_spec.rb

This PR implements #232.  Currently, a cluster can have `engineering` and `customer` notes.  Admin users can view, create and update both kinds of notes, site contacts can view, create and update only `customer` notes.
@bobwhitelock I have a few questions:
1. Is this along the lines of what you were expecting?
2. I'm assuming that we want to add the ability for the `customer` notes to be edited created through the non-RailsAdmin UI.  Is that correct?
3. Do we use the RailsAdmin UI in production for creating/editing/deleting admin content?
4. Any other comments you have would be appreciated.

Cluster notes

---

app/models/user.rb
spec/models/user_spec.rb

This PR handles the case where an invalid (either syntactically or semantically) SSO token was leading to a server error, by instead making `User.from_jwt_token` return `nil` in those cases.
I've also added a couple of tests for that method.
Trello: https://trello.com/c/xdF4dcDH/349-fix-500-when-sso-token-verification-fails

Handle invalid SSO tokens without raising HTTP 500 errors

---

app/controllers/case_comments_controller.rb
app/controllers/cases_controller.rb
app/models/case.rb
app/models/case_commenting.rb
app/policies/case_policy.rb
app/views/cases/_case_comment_toggle_controls.html.erb
app/views/cases/show.html.erb
config/routes.rb
db/migrate/20180611103418_add_comments_enabled_to_case.rb
db/schema.rb
spec/features/case/show_spec.rb
spec/models/case_commenting_spec.rb

This PR allows contacts to comment on tier 1/2 cases, where they otherwise would not be able to, when permitted to do so by an admin.
Admins viewing open tier 1/2 cases will now see an option to enable commenting for contacts. For cases where commenting has been enabled, they will see a similar option to disable commenting.
Note that there's a display bug here: the `a.btn` within the `.alert` is being given a `text-decoration: underline;` that it shouldn't. I've fixed this already in one of the other branches I've been working on where this came up, so it'll be resolved when that branch gets merged into develop.
Closes #319.
Trello: https://trello.com/c/kcUUpdIh/341-allow-admins-to-enable-disable-user-communication-box-on-a-tier-1-2-case

Allow enabling contact comments on tier 1/2 cases

---

app/controllers/cases_controller.rb
app/helpers/application_helper.rb
app/javascript/packs/Issue.elm
app/javascript/packs/Issues.elm
app/javascript/packs/Main.elm
app/javascript/packs/Msg.elm
app/javascript/packs/SelectList/Extra.elm
app/javascript/packs/Service.elm
app/javascript/packs/State/Update.elm
app/javascript/packs/new_case_form.js
app/views/cases/new.html.erb
app/views/clusters/_details.html.erb
elm-package.json
spec/controllers/cases_controller_spec.rb
spec/factories/issue.rb
spec/factories/tier.rb

This PR adds a button on the cluster's overview in the MOTD section to display the case form ready populated for creating a "MOTD change request".  
This works by adding `data-selected-category` and `data-seleted-issue` to the `new-case-form` DOM element which are passed into the elm app along with the other flags.  The elm `init` function then returns a list of `Cmd Msg`s to set the desired category and issue.
Whist this works, it would be better to have `decodeInitialModel` set the desired category and issue from `flags`.  Doing that would avoid a couple of trips through the elm runtime.  Unfortunately, how to do that is not immediately obvious to me.
Still to do: ~tests~

motd change request button

---

app/views/case_mailer/comment.html.erb
app/views/case_mailer/new_case.html.erb
app/views/layouts/mailer/_inline_main.scss

Hopefully this will stop Mark's email client from getting confused.
Fixes #335.
Trello: https://trello.com/c/VoWTgepK/348-blockquote-tag-in-email-confuses-airmail-email-client

Use a styled `div` rather than `blockquote` in emails.

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/cases.scss
app/views/partials/_case_table_row.html.erb

This PR highlights and makes the case row clickable. On click the user is redirected to the associated case page, just like the link via the case ID on the current site. However the links in the `Association` column still function as before.
During review it would be worth experimenting with the opacity within the `case-highlight` class found within `cases.scss`. You may find it looks better without any change in opacity but the option is there if you did want it that way.
It is also worth checking that links in the row are still distinct enough to stand out. I experimented with various css changes to try and find something that worked but it may not be enough.
[Trello](https://trello.com/c/tzcE8SSw/350-make-clicking-anywhere-on-case-row-in-table-link-to-case-page)

Clickable case row

---

app/views/clusters/credit_usage.html.erb
app/views/partials/_case_table_row.html.erb

By directly setting `window.location.href` in JS, these event handlers
were causing full page refreshes, slowing down the navigation and making
this transition more jarring than normal navigation via `a` links etc.,
which uses Turbolinks. Using `Turbolink.visit` in these places instead
fixes this.
Fixes
https://trello.com/c/2lJRAgSV/356-prevent-full-page-refresh-from-couple-of-places-using-windowlocationhref.

Use Turbolinks.visit to avoid full page refresh

---

app/assets/javascripts/application.js
app/decorators/audited/audit_decorator.rb
app/decorators/case_comment_decorator.rb
app/decorators/case_state_transition_decorator.rb
app/decorators/credit_charge_decorator.rb
app/decorators/log_decorator.rb
app/decorators/maintenance_window_state_transition_decorator.rb
app/views/cases/_event.html.erb

The changes made in this PR are somewhat subtle but that is by design. Making the cards more distinguishable without making them intrusive and ugly proved problematic. Therefore I opted with using Boostrap Tooltips that give more context to the icons when the user hovers over them. Hopefully this should clear any confusion that comes from these.
This had the knock on effect of making other areas where we use `title` as a tooltip to use this Bootstrap styling for them. Which should make those look a bit nicer than before as well.
[Trello](https://trello.com/c/Fvlb0KFq/352-consider-distinguishing-case-history-cards-more)

Distinguish case history cards more

---

app/controllers/cases_controller.rb
app/helpers/application_helper.rb
app/javascript/packs/Main.elm
app/javascript/packs/new_case_form.js
spec/controllers/cases_controller_spec.rb

In the tool preselection PR #346 it was decided that this code should be removed as there are a couple of edge cases and currently no requirement for the functionality.  It is now belatedly removed.

Remove unwanted code

---

app/assets/stylesheets/cases.scss
app/helpers/application_helper.rb
app/views/partials/_case_table_row.html.erb
app/views/partials/_table_cell_link.html.erb

This PR refactors the case row to have the same functionality as https://github.com/alces-software/alces-flight-center/pull/352 but with the added ability of being able to use the middle mouse button and context menu on the row.
[Trello](https://trello.com/c/wY2zsKw5/358-middle-click-on-case-row-should-open-case-in-new-tab-but-does-nothing)

Basic mouse functionality on case row

---

app/controllers/application_controller.rb
app/controllers/maintenance_windows_controller.rb
app/decorators/application_decorator.rb
app/javascript/packs/State.elm
app/javascript/packs/State/View.elm
app/javascript/packs/Tier/Field.elm
app/javascript/packs/View/PartsField.elm
app/models/cluster.rb
lib/alces/mailer/resender.rb
spec/decorators/case_decorator_spec.rb
spec/factories/case.rb
spec/models/cluster_spec.rb

All comments marked by `XXX` have been extracted to a card on the [Trello Board](https://trello.com/b/MIHTL78g/alces-flight-center-backlog) bar one which I fixed in 1c19265
[Trello](https://trello.com/c/5L1RXet9/247-grep-and-fix-move-into-trello-all-xxxs)

Extract comments to trello

---

app/controllers/application_controller.rb
app/controllers/cases_controller.rb
app/models/cluster.rb
spec/controllers/cases_controller_spec.rb
spec/controllers/clusters_controller_spec.rb
spec/features/maintenance_windows_spec.rb
spec/requests/navigation_variable_assignments_spec.rb

This PR utilises the cluster shortcode to create a vanity URL for cluster related links.
[Trello](https://trello.com/c/TuSECh2A/357-use-cluster-shortcode-in-links-to-cluster)

Cluster shortcode in links

---

app/models/credit_charge.rb
app/models/credit_deposit.rb
spec/controllers/clusters_controller_spec.rb
spec/models/credit_charge_spec.rb
spec/models/credit_deposit_spec.rb

Both credit charging and depositing should now properly enforce validity checks.
[Trello](https://trello.com/c/VCZW5HW3/362-creditcharge-and-creditdeposit-validations-not-working)

Credit charge and deposit validations

---

Gemfile
Gemfile.lock
app/controllers/application_controller.rb
app/views/errors/not_found.html.erb
app/views/sessions/_sign_in_box.html.erb
app/views/sessions/new.html.erb
spec/features/errors_spec.rb
spec/features/sessions_spec.rb
spec/rails_helper.rb

Since the switch to Flight SSO-based login, it's been possible for users to enter a state where they are logged in to the Flight platform but do not have a Flight Center account associated with their SSO account.
This is an entirely valid state, since anyone can sign up for Flight SSO but only those with the anointing can use Flight Center.
This PR allows Flight Center to identify users in this state, and tailors the text displayed to them where appropriate.
I've also added a test documenting the behaviour of the root path for given states of logged-in-ness.
Trello: https://trello.com/c/RHKYWl0r/355-differentiate-user-not-logged-in-and-user-logged-in-to-sso-but-has-no-flight-account

Differentiate users not logged in, and logged in without Center accounts

---

app/decorators/change_request_state_transition_decorator.rb
app/views/cases/_event.html.erb
spec/decorators/application_decorator_spec.rb
spec/factories.rb
spec/factories/maintenance_window.rb
spec/features/case/show_spec.rb

When I added tooltips to icons for case events in #357 I didn't account for new event cards missing a `details` key-value pair. However this should now assign a nil value to `details` if it is unable to find a value for the event card and therefore would not display any tooltip when hovering over the affected icon.

Prevent missing event details from breaking case page

---

app/controllers/change_requests_controller.rb
app/mailer_previews/case_mailer_preview.rb
app/mailers/case_mailer.rb
app/models/slack_notifier.rb
spec/controllers/change_requests_controller_spec.rb
spec/mailers/case_mailer_spec.rb

This PR adds Slack notifications for whenever a change request event sends an email out. These will be displayed like so:
With links to both the associated case and the change request itself.
[Trello](https://trello.com/c/8XlyhP8U/359-add-slack-notifications-to-change-request-events)

Change request event Slack notifications

---

app/views/cases/_escalation_controls.html.erb
app/views/change_requests/state_controls/_awaiting_authorisation.html.erb
app/views/change_requests/state_controls/_draft.html.erb
app/views/change_requests/state_controls/_in_handover.html.erb
app/views/change_requests/state_controls/_in_progress.html.erb
spec/features/change_request/show_spec.rb

This PR updates the guards around CR state buttons (including the initial "create CR" button) to use `Policy`s, consistent with the rest of the site. (`Policy` and friends weren't around when the work on CRs was started.)
Trello: https://trello.com/c/7JKGHzZv/361-improve-user-authorisation-handling-once-cr-pr-merged

Use policies to control visibility of CR state buttons

---

app/assets/stylesheets/application.scss
app/views/layouts/application.html.erb
config/environments/development.rb
config/environments/production.rb
config/environments/test.rb
lib/deployment.rb
lib/tasks/deploy.rake

This PR adds a version display just above the footer. Initially I have this in the format of `<year>.<version_number> <version name>` where `version_name` is a two word alliteration based on the `version_number` (If this equals 4 then use the 4th letter). With the first word being a verb and the second a bird.
As it stands the `version_name` shows up everywhere but `Production`. However this can easily be changed, as well as the actually formatting of the version display.
Note: There is currently nowhere stating that this needs to be changed between releases so finding a suitable place for that would be great
[Trello](https://trello.com/c/u07sGH6U/318-flight-center-version-display)

Version display

---

README.md
app/controllers/application_controller.rb
app/controllers/cases_controller.rb
app/controllers/change_requests_controller.rb
app/decorators/case_decorator.rb
app/decorators/component_decorator.rb
app/decorators/credit_charge_decorator.rb
app/decorators/service_decorator.rb
app/helpers/cases_helper.rb
app/helpers/mailer_helper.rb
app/models/application_record.rb
app/models/site.rb
app/models/slack_notifier.rb
app/policies/case_policy.rb
app/views/change_requests/show.html.erb
config/environments/test.rb
config/routes.rb
spec/features/case/new_spec.rb
spec/features/case/show_spec.rb

This PR lays some groundwork for multiple `Case` associations by reducing the number of URLs at which a `Case` can be viewed.
- The "canonical" path for a case is now `/clusters/:cluster_id/cases/:id`. 
- Actions on cases still happen at `/cases/:case_id/<action>`; these URLs are not visible to users and typically result in a redirect to the canonical path at the end of the action.
- Legacy URLs such as `/cases/:id`, `/sites/:site_id/cases/:id`, and those for `Service`s and `Component`s, redirect to the canonical URL - the latter two ignore the service/component ID entirely since this will no longer be a permanent way of identifying a case.
- Case lists for components and services no longer exist. They will be replaced in due course by filters on the case index pages.
Trello: …

Reduce number of case URLs

---

app/controllers/logs_controller.rb

This is a minor fix for something I came across the other day. Where the `SlackNotifier` was being called within the `LogsController` meant that a notification was being sent to Slack regardless of the validity of the log (woops).

Prevent slack notification for invalid logs

---

app/javascript/packs/new_case_form.js

According to
https://github.com/turbolinks/turbolinks#restoration-visits:
> If possible, Turbolinks will render a copy of the page from cache without making a request.
When navigating away and back to the Case form this was happening, and
so a cached version of the Case form was being displayed.
However, due to our use of `!target.hasChildNodes()` when deciding
whether to initialize the Case form, although the page looked correct
due to the cached HTML, the corresponding JS (compiled Elm) was not also
being initialized, and so the form did not have any of the intended
dynamic functionality and could not be submitted.
A heavy-handed way to fix this would be to set a `<meta
name="turbolinks-cache-control" content="no-cache">` tag on this page
and avoid Turbolinks caching this page …

Fix Case form breaking after history navigation (fixes #407)

---

.env.example
Gemfile
Gemfile.lock
app/assets/stylesheets/sites.scss
app/controllers/terminal_services_controller.rb
app/controllers/users_controller.rb
app/decorators/site_decorator.rb
app/models/concerns/admin_config/encryption_key.rb
app/models/concerns/admin_config/flight_directory_config.rb
app/models/encryption_key.rb
app/models/flight_directory_config.rb
app/models/site.rb
app/policies/flight_directory_config_policy.rb
app/views/sites/show.html.erb
config/initializers/cors.rb
config/routes.rb
config/secrets.yml
db/migrate/20180702095222_create_flight_directory_config.rb
db/migrate/20180709091730_create_encryption_keypairs.rb
db/migrate/20180709104724_add_ssh_key_to_flight_directory_config.rb
db/schema.rb
lib/tasks/encryption_keypair.rake

This PR adds support for the new flight terminal services client.
The purpose of the terminal services is to provide convenient in-browser access to some of our CLI admin tools.  Currently this is limited to the flight directory tool.
The support required from Center is:
1. A new model `FlightDirectoryConfig` belonging to `Site` which stores the hostname and username for SSH access to the Flight Directory service.
2. An API to expose a sites configured terminal services.
3. An API to expose the current center user.
4. A button on the site overview dashboard to redirect to the terminal services client.
With that understood the PR should be straightforward.  If not, let me know what questions you have and I'll answer as best I can.

Support for flight terminal services

---

lib/tasks/data.rake

"Needed", in this case, equates to "user is not a member of the `docker` group" which is the standard way of allowing non-root Docker access, at least on Debian-based systems.
@atoghill You might want to add your user to the `docker` group in your VM, but this PR shouldn't make any difference to you.

Don't use `sudo` to invoke `docker` unless it's needed.

---

config/environments/development.rb
config/environments/production.rb
lib/deployment.rb
lib/tasks/deploy.rake

This avoids conflicts with the `VERSION` var used by Rails's database migration tasks.

Rename version environment variable to `FC_VERSION`.

---

db/data/20180716101913_delete_audits_caused_by_migration.rb
db/data_schema.rb

Remove junk audits created by a previous data migration.

---

app/assets/javascripts/cluster_tree.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/cases.scss
app/assets/stylesheets/clusters.scss
app/controllers/cases_controller.rb
app/decorators/cluster_part_decorator.rb
app/decorators/component_decorator.rb
app/decorators/component_group_decorator.rb
app/decorators/service_decorator.rb
app/helpers/tabs_builder.rb
app/models/all_sites.rb
app/models/case.rb
app/models/component_group.rb
app/models/concerns/filterable.rb
app/views/case_associations/_cluster_part.html.erb
app/views/case_associations/_cluster_tree.html.erb
app/views/case_associations/edit.html.erb
app/views/cases/filters/_assigned_to.html.erb
app/views/cases/filters/_associations.html.erb
app/views/cases/filters/_filter_for.html.erb
app/views/cases/filters/_state.html.erb
app/views/cases/index.html.erb
app/views/partials/_case_table_row.html.erb
app/views/partials/_table.html.erb
config/routes.rb
spec/features/case/index_spec.rb
spec/helpers/tabs_builder_spec.rb

This PR adds the ability to filter the cases index page by state, assignee or association. It also replaces the separate `/resolved` cases index page with an appropriate filter query.
Filters are combined with `and`. Individual filter options are combined with `or`. For example: 
```
(assigned_to Ruan OR Andrew) 
AND 
(state Resolved OR Closed)
```
We reuse the cluster tree component to filter by component/service associations. For admins on the "all cases for all sites" page, this can also be used to filter by cluster (though at some point we'll run into URL length limit problems, since its method of doing so is by setting a filter for each cluster component - but it works for now).
Trello: https://trello.com/c/5XYwNUyb/368-add-filters-to-case-index-page
(Sidebar: the Trello card …

Filter case index page

---

app/models/change_request.rb
spec/models/change_request_spec.rb

Use correct Rails incantation to validate that CR charge >= 0.

---

app/models/user.rb
db/migrate/20180719092649_remove_passwords_from_users.rb
db/schema.rb
lib/deployment.rb
lib/tasks/data.rake
lib/tasks/deploy.rake
spec/factories/user.rb
spec/lib/tasks/deploy_spec.rb

This PR removes the requirement for users to have local passwords set. These passwords are no longer used since we have adopted Flight SSO.
It also removes the step of changing passwords on staging, for the same reason. (Changing of email addresses still happens.)
Fixes #436.
Trello: https://trello.com/c/Xx2Q2o4f/387-remove-local-password-requirement-for-users

Remove local passwords for users

---

app/assets/javascripts/application.js

We don't need to initialise the Bootstrap `Collapse`s used by the cluster tree, since they are initialised individually by the `_init_cluster_tree` function. Doing so was interacting badly with the Flight chrome navbar which also uses a `.collapse`.
Fixes #449.

Don't initialise `collapse`s on page transition.

---

app/decorators/credit_charge_decorator.rb
app/models/case.rb
app/models/credit_charge.rb
app/models/credit_deposit.rb
app/models/credit_event.rb
config/initializers/time_formats.rb
db/data/20180724162117_add_effective_dates_to_credit_charges.rb
db/data_schema.rb
db/migrate/20180724142635_add_effective_date_to_credit_charge.rb
db/schema.rb
spec/features/cluster/credit_usage_spec.rb

This PR adds an `effective_date` to the `CreditCharge`s associated with cases, which is set to the date of resolution of the associated `Case` at the point the `CreditCharge` is created.
For cases with no resolution date (e.g. old cases that were resolved before we started tracking state in Flight Center) the RT-derived `completed_at` date is used, and failing that, the `created_at` date of the case. This is consistent with [the logic we used to update these dates at the last release](https://github.com/alces-software/alces-flight-center/blob/master/db/data/20180703094017_adjust_credit_charge_creation_dates.rb).
We then use the `effective_date` to filter and display `CreditCharge`s for a `Cluster`.
Fixes #388.
Trello: https://trello.com/c/fCQDbGtv/391-credit-reporting-should-use-date-of-ca …

Use case resolution date for credit reporting

---

config/initializers/time_formats.rb

Drop "am/pm" suffix from 24-hour times.

---

app/views/layouts/mailer/_inline_main.scss

FSR Roadie was having trouble with inlining some of the more complicated bits of Bootstrap's table styles that we were importing to make Markdown tables look prettier.
This commit solves the resulting warning spam by copy/pasting the relevant parts of Bootstrap's table styles, rather than `@import`ing them. This should have no discernable difference on email appearance
since the parts Roadie was complaining about weren't actually used by us.
Fixes #461.

Avoid Bootstrap styles that Roadie can't handle.

---

app/javascript/Cluster.elm
app/models/cluster.rb
spec/factories/cluster.rb
spec/models/cluster_spec.rb

This was added in
https://github.com/alces-software/alces-flight-center/commit/1c192659,
however prior to being added several Clusters were created with empty
MOTDs. This was then causing these Clusters to be invalid, which in turn
was causing submitting the new Case form for these Clusters to fail.
Since:
a. things have otherwise been working fine with blank Cluster MOTDs
until this validation was added;
b. from a business perspective, Clusters are allowed to not have MOTDs,
since these Clusters were created without a MOTD set,
we have decided to remove this validation.
Also removed this field from the Cluster factory, since this is no
longer required to create a minimal Cluster, which then prompted the
need to handle the case where the MOTD is null in the new Case form (by
these tests …

Remove unneeded MOTD presence validation

---

app/controllers/application_controller.rb
app/controllers/root_controller.rb

After extracting the RootController, for all controllers which will be
used by our app to inherit from (including those which come from other
Gems like rails-admin), the extra Sentry Raven context which we set in
the ApplicationController was no longer being applied to these other
controllers. This was then causing errors like
https://sentry.io/alces-software-ltd/alces-flight-center/issues/626456706
to not include this additional identifying context, such as the User who
triggered the exception.
The straightforward fix for this is to just extract setting this context
up a level to the RootController as well.
(Not actually manually tested this yet, since that would require a deploy to staging I think. It _should_ be trivial enough to Just Work, but you can never tell with Ruby. Possibly …

Set Sentry error context for rails-admin controllers

---

app/controllers/cases_controller.rb
app/decorators/cluster_decorator.rb
db/data/20180727161526_create_other_issues.rb
db/data_schema.rb
spec/decorators/cluster_decorator_spec.rb

This PR adds an injected 'Other' Service, along with 2 'Other' Issues - one which `requires_service` and one which doesn't. These are the first minimal changes to address https://github.com/alces-software/alces-flight-center/issues/361 - whether and how much these changes improve the situation discussed there remains to be seen.
The core of these changes is the 'Other' Service injection from the experimental branch linked in that issue (thanks @jamesremuscat!); also included is test coverage for this change, fixing of existing tests, the addition of the Issues needed to work with this change, and some other tidying/refactoring to hopefully make this change clearer and more robust.
Trello: https://trello.com/c/EUGNoYqY/410-add-other-service-and-issue-to-facilitate-tier-3-ticket-creation.

'Other' Service and Issues

---

app/controllers/cases_controller.rb
app/decorators/audited/audit_decorator.rb
app/mailers/case_mailer.rb
app/models/case.rb
app/policies/case_policy.rb
app/views/case_mailer/change_subject.html.erb
app/views/case_mailer/change_subject.text.erb
app/views/cases/show.html.erb
app/views/layouts/application.html.erb
config/routes.rb
spec/features/case/edit_spec.rb

This PR allows admins to edit the subject of a `Case` after it has been created.
Admins will now see an "edit" button (pencil icon) next to the title of a `Case`. Clicking it will reveal an input field for them to alter the title. Doing so will generate an email and an event card in the case history.
I've also tried to implement this in a generic enough way that editing other fields will be an easy and logical follow-on, which might also help if we decide to do #396.
One half of the remnant of #72.
Trello: https://trello.com/c/kIiobw6i/393-allow-admins-to-change-subject-of-cases

Allow admins to edit case subject

---

app/models/case.rb
app/views/cases/associations/_association_info.html.erb
app/views/partials/_association_summary.html.erb
spec/features/case_associations/edit_spec.rb
spec/models/case_spec.rb

Since we're now allowing cases to be created with no associations via the "Other" pseudoservice/issue, it looks a bit jarring to then be presented with "the entire cluster is affected!!!" the moment you submit.
This removes the default association from `Case`s and adds placeholder "None" text in places that would otherwise be empty as a result.
See https://github.com/alces-software/alces-flight-center/pull/465#issuecomment-409570574 for full justification.
Trello: https://trello.com/c/AowM4v1p/417-dont-default-to-whole-cluster-association-for-cases

Don't default to cluster if case associations are empty.

---

app/controllers/cases_controller.rb
app/decorators/audited/audit_decorator.rb
app/decorators/case_decorator.rb
app/decorators/issue_decorator.rb
app/mailers/case_mailer.rb
app/models/case.rb
app/views/case_mailer/change_issue_id.html.erb
app/views/case_mailer/change_issue_id.text.erb
app/views/cases/_issue_controls.html.erb
app/views/cases/show.html.erb
spec/decorators/case_decorator_spec.rb
spec/decorators/issue_decorator_spec.rb
spec/features/case/edit_spec.rb

This PR finally fixes #72 by adding the ability for admins to edit the `Issue` associated with a `Case` - with an important restriction.
Admins now see a dropdown list of all `Issue`s that could validly be associated with a `Case`, and can change this as they desire. An entry in the case history feed and an email are generated when they do so. Non-admins (or rather, those without permission to `edit?` a `Case`) see no different.
The restriction is that only `Issue`s against which the current `Case` would be valid are permitted. That is, the only permitted `Issue`s are those which require no specific `Service`, or those which require a `Service` to which the `Case` is currently associated. (Admins are able to add more `Service` associations to broaden the list of available `Issue`s if …

Allow admins to edit case issue

---

app/decorators/cluster_decorator.rb
app/views/partials/_nav_link.html.erb

This isn't a long-term solution, but it works for now. If we start adding yet more things to the tab bar we'll want to do something more drastic (like implementing support for nested dropdowns, or some other reorganisation of the site layout).
Trello: https://trello.com/c/6DUMY2Ls/415-reorganise-cluster-dashboard-tabs

Merge the Services and Components tabs into one to save space.

---

app/controllers/change_requests_controller.rb
app/policies/change_request_policy.rb
app/views/change_requests/_form.html.erb
app/views/change_requests/_markdown_content.html.erb
app/views/change_requests/preview.html.erb
app/views/change_requests/write.html.erb
config/routes.rb

When creating or editing a change request you can now preview the `Description`. The old textbox has been replaced with a Markdown editor that has a `Write` and `Preview` button, just like in other areas of Flight Center.
[Trello](https://trello.com/c/ZfJqvCZh/363-markdown-preview-for-change-requests)

Markdown preview for change requests

---

config/initializers/sentry.rb

This PR makes two changes to our Sentry configuration:
- We now set the value of `release` to the Flight Center version number (taken from `ENV['FC_VERSION']`)
- Exceptions are submitted asynchronously to Sentry via our Resque/Redis instance. Hopefully this will mean that exceptions no longer cross threads and appear where they shouldn't (see Trello card linked below).
No changes were necessary to the Redis or Resque configuration. Sentry tasks will be picked up by the existing Resque worker process.
Trello: https://trello.com/c/wC2DpSaQ/390-use-async-jobs-to-send-errors-to-sentry

Sentry configuration enhancements

---

app/views/clusters/enter_check_results.html.erb

The Command column within the cluster check result submission form is now wrapped in a `<code>` block so that it utilises the fancier Markdown code styling.
Example:
[Trello](https://trello.com/c/USAEAjkZ/421-utilise-markdown-code-styling-for-the-cluster-check-command-column-within-the-result-submission-form)

Utilise Markdown code styling for Command column (Cluster Checks)

---

app/assets/javascripts/datepicker.js
app/controllers/maintenance_windows_controller.rb
app/views/clusters/_deposit_form.html.erb
app/views/clusters/view_checks.html.erb
app/views/partials/_date_time_select.html.erb
spec/features/maintenance_windows_spec.rb

Date selection is now consistent for all three areas that require it; viewing check results, depositing credits and making a maintenance request. 
There are three separate definitions for the date picker, one for each use case. While these are not wholly necessary it might be useful for easier individual customisation. However it is also possible to alter many of the date picker options via helper methods.
Another thing to note is that the boxes for selecting the time are unchanged within the maintenance request form as the date picker only supports choosing the date. There is a Trello [card](https://trello.com/c/1yyrqJ63/233-consider-upgrading-date-picker-to-a-date-and-time-picker) for potentially upgrading the date picker to one that can handle both the date and the time. …

Consistent date entry fields

---

app/models/cluster/documents_retriever.rb

Rather than return a 500 error, better to just return an empty list if we can't access AWS.
Trello: https://trello.com/c/YyJD51D7/424-better-handle-aws-errors

Don't die horribly if there's an AWS error retrieving documents.

---

app/controllers/clusters_controller.rb

This should cull the amount of notifications that Slack receives per cluster check result log to a maximum of one. Woops.
[Trello](https://trello.com/c/htJSIkNI/425-prevent-potentially-infinite-slack-notifications-for-cluster-check-result-logs)

Prevent potentially infinite Slack notifications

---

app/views/clusters/_cluster_checks.html.erb

Any clusters that have no checks assigned to them will no longer display the cluster check widget on their dashboard.
[Trello](https://trello.com/c/AUku9vg6/426-hide-the-cluster-check-widget-if-the-cluster-has-no-checks-assigned)

Hide cluster check widget if the cluster has no assigned checks

---

app/controllers/change_requests_controller.rb
app/decorators/change_request_state_transition_decorator.rb
app/models/change_request.rb
app/models/change_request_state_transition.rb
app/policies/change_request_policy.rb
app/views/change_requests/state_controls/_awaiting_authorisation.html.erb
config/routes.rb
spec/features/change_request/show_spec.rb
spec/models/change_request_state_transition_spec.rb

With this PR a contact is now able to request changes to an active change request. This will return the CR to the `draft` state from which an admin can go in and make adjustments before submitting it for authorisation again.
As discussed in #486 the contact will then need to detail the changes they want in the comment section of the associated case.
[Trello](https://trello.com/c/NescjX8O/422-allow-users-to-request-changes-to-a-change-request)

Request changes to change requests

---

app/decorators/cluster_decorator.rb
app/models/cluster.rb
app/views/clusters/_cluster_checks.html.erb

When hiding the widget under the same circumstances in #498 I hadn't done the same for the `Checks` tab; see #501. This PR resolves this so that now if a cluster has no cluster checks **both** the widget and the tab are hidden.
[Trello](https://trello.com/c/GRU0oFKz/432-hide-cluster-checks-tab-when-a-cluster-has-no-associated-checks)

Hide checks tab when a cluster has no associated checks

---

app/models/cluster.rb
app/views/clusters/_credit_balance.html.erb

This PR addresses #389 by adding a visible count to indicate the number of resolved but unclosed cases for a cluster. Visible on both the cluster dashboard and the credit usage page below the number of available credits:
[Trello](https://trello.com/c/cvj2IK1I/409-show-number-of-resolved-but-unclosed-cases-on-credit-usage-page)

Display the number of resolved cases

---

app/controllers/cases_controller.rb
app/decorators/audited/audit_decorator.rb
spec/features/case/show_spec.rb

If both values are nil or empty then we unset `time_worked`; else we treat the missing value as 0 and take the time from the value that was given.
Refs #505.
Trello: https://trello.com/c/zubBs61C/436-handle-null-values-from-time-worked-form

Handle null values in time worked form.

---

app/assets/javascripts/application.js

Fixes #521.
Trello: https://trello.com/c/YdiIb9iX/437-fix-turbolinks-leaving-orphaned-popovers-tooltips

Clean up orphaned Bootstrap tooltips and popovers on Turbolinks load.

---

app/controllers/cases_controller.rb
app/decorators/case_decorator.rb
app/helpers/application_helper.rb
app/mailers/case_mailer.rb
app/models/case.rb
app/views/cases/index.html.erb
app/views/partials/_case_table_row.html.erb
db/data/20180814105742_populate_case_last_update_times.rb
db/data_schema.rb
db/migrate/20180814105312_add_last_update_to_cases.rb
db/schema.rb
spec/features/case/index_spec.rb
spec/models/case_spec.rb

This PR introduces a new field, `last_update`, to `Case`s, in order to track the last time it was updated by an admin (and therefore be able to calculate the time since the last such update).
There's a data migration here that initialises this value for all current cases:
- If the case is resolved or closed, we set `last_update` to the case's Rails automagic `updated_at` field.
- If it's open, then we consider the following events and take the date/time of the most recent (possibly null):
- Admin comments
- Maintenance window transitions
- CR transitions
- Edits to subject or issue
This corresponds to the list on #507 of things for which we currently send a customer-facing email.
Updating this field is handled by `CaseMailer`: every time an email is sent about a case that is received by …

Track time since last update for cases

---

app/decorators/case_decorator.rb
app/mailer_previews/admin_mailer_preview.rb
app/mailers/admin_mailer.rb
app/models/case.rb
app/models/user.rb
app/services/daily_admin_reminder.rb
app/views/admin_mailer/daily_open_cases_list.html.erb
app/views/admin_mailer/daily_open_cases_list.text.erb
app/views/layouts/mailer.text.erb
app/views/layouts/mailer/_inline_main.scss
lib/deployment/crontab.erb
lib/tasks/admin_mailer.rake
lib/tasks/cron.rake
spec/services/daily_admin_reminder_spec.rb

This PR introduces a new email, sent daily to admins, listing their currently assigned and unresolved cases.
They say a picture is worth a thousand words:
(Note: as in FC itself, hovering over the "Last update" entries will give the timestamp of the last update.)
Only admins currently assigned open cases will be sent an email.
A cronjob will be added to the server to run this task at 9am every weekday.
Part of #479. Fixes #417 (doesn't match the requirements stated there but exceeds them).
Trello: https://trello.com/c/c6xcgSZK/431-morning-update-email-for-admins

Daily reminder email for admins

---

app/models/cluster.rb
app/models/maintenance_window.rb
spec/features/maintenance_windows_spec.rb

Don't display the same maintenance window more than once.
Also tweaked the order in which we list associations for a MW to match that of cases.
Fixes #530, and should also become a hotfix release for 2018.6.

Maintenance windows should appear once on cluster dashboard

---

app/decorators/all_sites_decorator.rb

This value was still considering resolved/closed cases. It has been updated to only count the number of assigned cases that are open for the current user. Addresses a mistake in #542.
[Trello](https://trello.com/c/qPJRB17o/450-display-correct-number-of-assigned-open-cases-for-the-current-user-in-dropdown)

Display the correct number of open assigned cases in dropdown

---

db/migrate/20180823144957_change_markdown_columns_from_string_to_text.rb
db/schema.rb

Any Markdown related columns in the database have been updated to be of the `:text` variant. This should allow them to be edited correctly via the admin interface.
@mjtko let me know if this resolves your problem.
[Trello](https://trello.com/c/EuRY5Kei/454-ensure-markdown-columns-have-text-not-string-type)

Change Markdown columns data type to text

---

.env.example
README.md

Now that the Flight terminal service is starting to be used the `TERMINAL_SERVICE_BASE_URL` env var needs to be set in order for any site that is using this to have their main page working in `Development`. I have updated the `readme.md` and `.env.example` files to account for this.
[Trello](https://trello.com/c/qcMs8QKf/453-update-files-to-account-for-necessary-environment-variables-for-a-development-environment)

Update files to account for necessary environment variables for a development environment

---

app/decorators/case_decorator.rb
db/data/20180824162550_rename_servicey_other_issue.rb
db/data_schema.rb

This PR makes further changes to the "Other" issue functionality by distinguishing the names of the "Other" that requires a `Service` and the one that does not, and displaying them both in the issue-selection dropdown.
Before these changes, it was possible to encounter a confusing scenario as follows:
- Create a case with no service and "Other" issue
- Associate a service to the case
The original, serviceless "Other" would then no longer appear in the dropdown, meaning that no issue would be preselected and the case would appear to be associated with the first issue in the list. Now the serviceless "Other" is included in the options, and distinguished from the service-ful "Other" by changing the name of the latter.
Trello: https://trello.com/c/vtcgGurR/456-further-other-tweaks

Fix confusion caused by two "Other" issues

---

app/assets/javascripts/cluster_tree.js
app/controllers/case_associations_controller.rb
spec/features/case_associations/edit_spec.rb

As title.
Trello: https://trello.com/c/fFnYjfNT/455-allow-case-association-form-to-clear-all-associations

Allow case association form to be submitted when empty.

---

app/views/cases/show.html.erb
app/views/partials/_case_table_row.html.erb

Fixes #503.
Trello: https://trello.com/c/VHXLdXBk/444-italicise-date-and-creator-in-case-created-column

Italicise name and date when showing case creation details.

---

app/assets/stylesheets/clusters.scss
app/assets/stylesheets/sites.scss
app/decorators/cluster_decorator.rb
app/models/cluster.rb
app/models/service_plan.rb
app/views/clusters/_credit_balance.html.erb
app/views/clusters/_details.html.erb
app/views/clusters/credit_usage.html.erb
app/views/sites/_cluster_box.html.erb
app/views/sites/show.html.erb
db/migrate/20180828100631_create_service_plans.rb
db/schema.rb
spec/factories.rb
spec/models/cluster_spec.rb

This PR fixes #403 by adding the concept of "service plans", associated with clusters, and displaying that information in a variety of places.
On the site dashboard:
With different colours for nearly-expired and expired service plans:
For each period viewed on the credit usage report, we list any overlapping service plans:
and warn when the period is not covered by a service plan:
@mjtko @ste78 Any comments or changes you'd like to how this information is presented?
Trello: https://trello.com/c/VicFrPKR/443-store-and-display-service-plan-dates-for-clusters

Display cluster service plan dates

---

app/controllers/change_requests_controller.rb
app/decorators/change_request_state_transition_decorator.rb
app/mailers/case_mailer.rb
spec/controllers/change_requests_controller_spec.rb

This PR fixes #487 by changing the text of the CR-proposed email to use "your" rather than "customer", and the article from "the" to "a" everywhere this text is used.
Trello: https://trello.com/c/jUxmNlgo/438-update-text-in-cr-proposed-email

Update CR email text

---

app/decorators/cluster_decorator.rb
app/decorators/service_decorator.rb
app/models/case.rb
app/models/case/issue_validator.rb
app/models/case_commenting.rb
app/models/maintenance_window.rb
app/models/maintenance_window/validator.rb
app/views/cases/show.html.erb
db/data/20180829150212_add_administrative_issue.rb
db/data_schema.rb
db/migrate/20180829145124_add_administrative_to_issues.rb
db/schema.rb
spec/factories/issue.rb
spec/mailers/case_mailer_spec.rb
spec/models/case_commenting_spec.rb
spec/models/maintenance_window_spec.rb

This PR introduces the concept of "administrative" cases - that is, cases that are read-only for site users.
We achieve this by introducing a new class of `Issue` available only to admins, `administrative`; cases with an administrative issue set enjoy a reduced set of functionality:
- Site contacts (and viewers) are unable to comment
- Emails are not sent to site email addresses
- Maintenance cannot be requested (nor can a case with outstanding maintenance windows be assigned an administrative issue) since this presupposes interaction with customers
Other than in the scenario outlined above, it's possible to move a case into and out of being "administrative" by changing its assigned issue. Usual restrictions (issues requiring a service need the case to have an association to that sort of …

Administrative cases

---

app/mailers/admin_mailer.rb

Because of the way we serialise/deserialise mailer arguments through Resque, we need to treat `cases` here as an array, not an ActiveRecord association (it doesn't have a `decorate` method).

Fix handling daily admin mail via Resque

---

app/models/component.rb

Allow empty string for component info (disallow nil).

---

app/models/case.rb
app/policies/case_policy.rb
spec/features/case/show_spec.rb
spec/models/case_spec.rb

When an administrative case has been created it will no longer assign a default contact to the case. To ensure contacts are not assigned after this the contact assignment controls are disabled for such cases and attempting to assign a contact via the rails admin interface will throw a validation error.
[Trello](https://trello.com/c/9Lh1Rbtx/457-no-site-assignee-should-be-set-for-administrative-cases)

Don't assign contacts to administrative cases

---

app/controllers/topics_controller.rb
app/policies/topic_policy.rb
config/routes.rb

The `flight support` cluster CLI tool is to be available to cluster users.  We wish to provide them with access to the support topics and articles for their site/cluster and to use the tool to drive them towards the Flight Platform.
When a cluster user uses the tool, they will be prompted to sign up / sign in to the Flight Platform by using the `flight account` CLI tool.  When they have done so they can use `flight support` to view the support topics.  We don't require a Center account for such users as we 1) wish to avoid having to create lots of accounts in Center; and 2) Center is focused on cluster administrators not cluster users.
Currently, a request from a cluster user will display only global (non-site specific) topics.  Eventually, the HTTP request will be augmented to include …

Global topics (and articles) are available to all flight platform users

---

app/assets/stylesheets/application.scss
app/helpers/scope_nav_links_builder.rb
app/views/partials/_nav_link.html.erb
app/views/partials/_site_picker.html.erb
spec/features/nav_bar_spec.rb

This PR gives admins a quick-access dropdown to switch between sites:
It does pretty much what you'd expect. The site name remains a link the site dashboard, only the caret toggles the dropdown (though 'Choose site' also toggles the dropdown).
Trello: https://trello.com/c/Z60a7m88/459-quick-site-switcher-for-admins

Add a site picker dropdown for admins

---

app/controllers/sites_controller.rb
app/models/site.rb
app/views/partials/_site_picker.html.erb

I can't think of a way to do this other than to comment it out and later re-enable it once we've deployed this live. Answers on a postcard please...

Avoid using `:identifier` for default scope before it exists.

---

app/mailer_previews/admin_mailer_preview.rb
app/mailers/admin_mailer.rb
app/services/daily_admin_reminder.rb

I'm not quite sure why the `daily_open_cases_list` method is now [being passed a Hash](https://sentry.io/alces-software-ltd/alces-flight-center-staging/issues/676737736) rather than [the array it was being passed](https://sentry.io/alces-software-ltd/alces-flight-center-staging/issues/672529010) when I applied the last bugfix (#561). But since passing ActiveRecord objects through Resque is clearly so unreliable, let's just bypass the issue by sending an array of IDs and rehydrating them in Resque-runner-land.

Try again to get daily admin emails working

---

db/data/20180831145350_initialise_assigned_contacts_for_open_cases.rb

This should now ensure that the migration correctly does what it is told and all open cases will now have an assigned contact.
Once merged this fixes #589
[Trello](https://trello.com/c/s4QfEIfk/460-fix-migration-for-assigning-contacts-to-currently-open-cases)

Correctly assign contacts to open cases

---

app/decorators/all_sites_decorator.rb

The landing page for admins is now the first tab on the Global Dashboard which fixes #564.
[Trello ](https://trello.com/c/8NFdvNqo/461-swap-order-of-tabs-on-the-global-dashboard)

Swap the tabs around within the Global Dashboard

---

app/models/case.rb

The dropdown box for assigning an engineer to a case was not sorted, making it a pain to find the user you wanted to select. Now both the assignment dropdowns are sorted by name hopefully making this process a
bit easier.
Fixes #590 
[Trello](https://trello.com/c/zeHr5mmu/473-sort-assignment-controls-by-name)

Order users in assignment controls by name

---

app/models/case.rb
spec/features/case/new_spec.rb

If an admin creates a case then they are automatically assigned as the engineer for that case, regardless of their status as default assignee.
Fixes #591 
[Trello](https://trello.com/c/jdRlWghG/474-if-an-admin-creates-a-case-assign-them-as-the-engineer-for-it)

Assign cases to admins when they create a case

---

app/assets/stylesheets/sites.scss
app/controllers/terminal_services_controller.rb
app/decorators/cluster_decorator.rb
app/decorators/site_decorator.rb
app/models/cluster.rb
app/models/cluster_terminal_service.rb
app/models/concerns/admin_config/cluster_terminal_service.rb
app/models/concerns/admin_config/site_terminal_service.rb
app/models/concerns/admin_config/terminal_service.rb
app/models/site.rb
app/models/site_terminal_service.rb
app/models/terminal_service.rb
app/policies/cluster_terminal_service_policy.rb
app/policies/site_terminal_service_policy.rb
app/policies/terminal_service_policy.rb
app/views/clusters/_details.html.erb
app/views/clusters/_service.html.erb
app/views/sites/_service.html.erb
app/views/sites/show.html.erb
config/routes.rb
db/migrate/20180905115743_genericize_terminal_service_config.rb
db/migrate/20180905165332_add_ui_columns_to_terminal_services.rb
db/migrate/20180910010015_support_cluster_terminal_services.rb
db/schema.rb

This PR makes the terminal services more generic in two distinct ways.
The first of these is to remove all hardcoding of a "directory" terminal
service.  To do this each terminal service now has a `service_type` which
identifies the particular service.  This is used by the terminal service API
and client to request the correct terminal service configuration.
The hardcoding has also been removed from the Center and console UIs; the
terminal services now contain a JSON blob which the Center and console UI
use to construct their respective UIs.
The second way in which the terminal services are more generic is that it is
now possible for clusters to have terminal services.  This has been
implemented with STI and splitting the `TerminalService` model into
`SiteTerminalService` and …

Genericise terminal service configs

---

app/controllers/clusters_controller.rb
app/models/cluster.rb
app/models/cluster/documents_handler.rb
app/policies/cluster_policy.rb
app/views/clusters/documents.html.erb
config/routes.rb
spec/features/cluster/documents_spec.rb
spec/features/cluster_tabs_spec.rb
spec/fixtures/test-upload.txt

This PR enables engineers to upload files directly to the S3 bucket from the cluster documents page.
Files are automatically uploaded to the correct bucket and path based on environment/site/cluster. I've modified the `AlcesFlightCenterS3Access` IAM policy to allow Flight Center to `PutObject` within its bucket. As with current files, world-readable permissions are *not* set, nor are they required - we generate a pre-signed URL when making them available through the Documents page.
As with the existing S3 document functionality, all uploaded documents are made available to engineers and to all site users.
Fixes #492.
Trello: https://trello.com/c/3CmfIjpV/464-upload-cluster-documents-to-s3

Upload documents to S3 bucket directly

---

app/views/partials/_site_picker.html.erb

This stops the arrow on the site picker from wrapping to a new line on Firefox.
[Trello](https://trello.com/c/EZe0deyz/475-fix-site-picker-arrow-on-firefox)

Fix the site picker arrow on Firefox

---

app/assets/stylesheets/cases.scss
app/decorators/case_state_transition_decorator.rb
app/views/cases/_event.html.erb

Closes #518 when merged
Currently looks like so 
How is this with people?
The icon wasn't my first choice but it seems like many are missing from rails-font-awesome (I thought [user-lock](https://fontawesome.com/icons/user-lock?style=solid) or [user-shield](https://fontawesome.com/icons/user-shield?style=solid) would probably be better)
Also had some issues (again) with the css - the hourglass appears much larger than the user-secret to me but both the icons are supposedly 32px tall. This made it fairly difficult to try and dynamically resize them to more similar heights, any ideas?

Add icon to hidden case events

---

app/views/cases/_escalation_controls.html.erb
spec/features/case/show_spec.rb

This PR removes the escalation warning dialog that popped up when trying to escalate a case to tier 3; it also changes the wording of the button to say "Open for comments" because "Escalate" is scary.
Fixes #577. Relates to #576, but only in passing.
Trello: https://trello.com/c/0c8A9L0O/465-make-escalate-button-less-scary-for-customers

Remove escalation confirmation modal and change button wording
