alces-software/alces-flight-center

- app/controllers/cases_controller.rb
- app/javascript/packs/Issue.elm
- app/javascript/packs/Main.elm
- app/javascript/packs/State.elm
- app/javascript/packs/View/Fields.elm
- app/models/case.rb
- app/models/issue.rb
- app/views/cases/_cases_table.html.erb
- db/data_migrations/20180131102517_set_token_and_subject_for_existing_cases.rb
- db/migrate/20180130092702_add_token_to_cases.rb
- db/migrate/20180130123030_add_subject_to_cases.rb
- db/schema.rb
- spec/controllers/cases_controller_spec.rb
- spec/features/cases_table_spec.rb
- spec/models/case_spec.rb
- spec/models/issue_spec.rb
I'll merge this straight through once confirming CI passes. This PR resolves a number of minor issues as reported in #37 and #41, see https://trello.com/c/0nb3bZ9R/154-various-ui-and-rt-ticket-format-tweaks for the specific user-facing changes made. When I merge it into `develop` I'll also rebase and merge it into `master` so we can put out a release without including the unfinished changes in `develop` related to #22.
> Various requested UI and ticket format tweaks (closes #37 and #41)

- .env.example
- Gemfile
- Gemfile.lock
- app/controllers/application_controller.rb
- config/initializers/sentry.rb
Following instructions at https://docs.sentry.io/clients/ruby/integrations/rails/.
Trello: https://trello.com/c/cwVn4vQh/88-add-some-error-monitoring.
> Setup Sentry for error monitoring

- app/controllers/asset_records_controller.rb
- app/controllers/component_expansions_controller.rb
- app/decorators/asset_record_field_decorator.rb
- app/helpers/application_helper.rb
- app/models/concerns/has_asset_record.rb
- app/views/component_expansions/edit.html.erb
- app/views/partials/_edit_submit_button.html.erb
- app/views/partials/_expansion_table.html.erb
- spec/features/asset_record_spec.rb
- spec/models/concerns/has_asset_record_spec.rb
This PR contains most requested fixes from the previous PRs. There are still a few changes to be made which will be based of this branch.
I have rebased on `develop` so the commit numbers have changed.
Please refer to the individual commits for the changes. A lot of them are small changes that are renaming variables.
> Assorted changes as requested by bob

- app/controllers/application_controller.rb
- app/controllers/asset_records_controller.rb
- app/controllers/component_expansions_controller.rb
- app/decorators/asset_record_field_decorator.rb
- app/decorators/asset_record_field_definition_decorator.rb
- app/models/concerns/has_asset_record.rb
- app/models/expansion.rb
- app/views/partials/_asset_record_table.html.erb
- spec/factories/asset_record_fields.rb
- spec/models/asset_record_field_definition_spec.rb
- spec/models/concerns/has_asset_record_spec.rb
- spec/models/expansion_spec.rb
Reasonable small PR based on #57 
It contains a few final commits of requested changes. Please refer to the commit messages for more details. Once this PR has been merged, then we can look at releasing it.
> Final tweaks for ComponentMake and Expansions

- Gemfile
- Gemfile.lock
- bin/generate-needed-null-constraint-migrations
- db/migrate/20180209120747_add_missing_null_constraints.rb
- db/migrate/20180209125114_add_missing_foreign_keys.rb
- db/schema.rb
- spec/models/cluster_spec.rb
This PR makes a couple of changes to improve the database, to try to avoid possible issues due to missing constraints or foreign keys. Specifically:
- add all the non-null constraints we are missing - see https://github.com/alces-software/alces-flight-center/commit/a1108014ebc0580f8f07df8880649fbf895079db, https://github.com/alces-software/alces-flight-center/commit/7c8679ce907968126951b2c4576b83d979f7d6f1, and https://github.com/alces-software/alces-flight-center/commit/ce6dad680b7a368d968d1bcf2b75bb0216bc65a1 for details;
- add all foreign keys we are missing - see https://github.com/alces-software/alces-flight-center/commit/704203c34a2945aee61728088bfe78bf6b444c6a for details.
I'll merge this through in a minute but feel free to have a look through/comment if you like.
Trello: …
> Tighten up data integrity

- app/assets/stylesheets/application.scss
- app/views/cluster_logs/index.html.erb
- bin/backup-database
- bin/import-production-data
Minor tweaks to backup process and styling; see commits.
> Minor tweaks

- app/services/progress_maintenance_window.rb
- spec/services/progress_maintenance_window_spec.rb
This PR addresses comments on #78. Based on #83.
> Address PR 78 comments

- app/models/maintenance_window.rb
Recreation of https://github.com/alces-software/alces-flight-center/pull/106 because I hit the wrong merge button.
> Dynamically determine finished MW states

- bin/backup-database
- bin/deploy-production
Recreation of #108 because I hit the wrong merge button.
> Remove containers when running dokku commands

- app/controllers/maintenance_windows_controller.rb
- app/helpers/date_time_select_helper.rb
- app/views/maintenance_windows/new.html.erb
- app/views/partials/_date_time_select.html.erb
- config/routes.rb
- spec/features/maintenance_windows_spec.rb
Recreation of #114 because I hit the wrong merge button.
> Display maintenance validation errors

- spec/features/maintenance_windows_spec.rb
- spec/rails_helper.rb
Recreation of #115 because I hit the wrong merge button.
> Refactoring maintenance form tests

- Gemfile.lock
- app/controllers/maintenance_windows_controller.rb
- app/models/maintenance_notifier.rb
- config/routes.rb
- spec/features/maintenance_windows_spec.rb
- spec/models/maintenance_window_spec.rb
This PR contains various refactoring and minor tweaks to the recent maintenance changes, see commits for details.
> Maintenance tweaks

- app/decorators/application_decorator.rb
- app/decorators/site_decorator.rb
This addresses a few of the comments on the previous PRs. See comments for details.
> Final tweaks for tabs

- app/controllers/application_controller.rb
- app/decorators/application_decorator.rb
- spec/support/shared_examples/case_form_buttons.rb
Just a couple of final tweaks.
Related card: https://trello.com/c/BEst8A6c/207-audit-language-titles-ui-things-etc-in-pages-after-tab-conversion.
> Final pre-deployment tweaks

- db/migrate/20180404160239_remove_legacy_maintenance_window_fields.rb
- db/migrate/20180404161446_make_maintenance_window_fields_non_nullable.rb
- db/schema.rb
Just a couple of data model simplifications now the latest maintenance changes have been deployed.
> Post-deploy tweaks

- app/controllers/cases_controller.rb
- app/models/case.rb
- app/models/issue.rb
- app/models/tier.rb
- db/migrate/20180409150804_create_tiers.rb
- db/schema.rb
- spec/factories/case.rb
- spec/models/case_spec.rb
- spec/models/tier_spec.rb
This PR makes the initial changes to add the `Tier` model and make associated Tier-related changes to the `Issue` and `Case` models.
Trello: https://trello.com/c/p4lDR8I7/218-add-capability-for-issues-and-cases-to-have-associated-tiers-tier-data-1-2-day
> Tier modelling

- app/javascript/packs/Main.elm
- app/javascript/packs/Msg.elm
- app/javascript/packs/State/Update.elm
- app/javascript/packs/State/View.elm
- app/javascript/packs/View/CaseForm.elm
- app/javascript/packs/View/Utils.elm
This PR contains refactors the Case form app to be more easily manageable, with different files containing what were previously the different parts of `Main.elm`.
> Refactor Case form app

- app/models/tier.rb
- spec/models/tier_spec.rb
Trello: https://trello.com/c/Hmo7hi2m/239-bonus-validate-issue-only-has-0-or-1-tier-at-each-possible-level-1-4-day.
> Validate only single Tier of level per Issue

- .env.example
- bin/import-production-data
- bin/setup
Couple of fixes I needed to make to get things running on my new laptop. Would be very useful if you could check these don't break `bin/setup` or `rake alces:data:import_production` for you when you get a chance @jamesremuscat :slightly_smiling_face:.
> Development fixes to run on my new machine

- app/controllers/case_comments_controller.rb
- app/decorators/case_decorator.rb
- app/models/case.rb
- app/views/cases/_email_support_icon.html.erb
- app/views/cases/index.html.erb
- app/views/cases/show.html.erb
- db/data_migrations/20180419111137_set_case_states_from_rt.rb
- spec/factories.rb
- spec/features/cases_spec.rb
- spec/features/log_spec.rb
- spec/features/maintenance_windows_spec.rb
- spec/models/case_comment_spec.rb
This PR includes a bunch of miscellaneous small changes requested in reviews of PRs #155 and #176.
Trello: https://trello.com/c/A0vo3WpP/229-look-at-comments-on-pr-155 / https://trello.com/c/vLvITAXP/248-look-at-comments-on-pr-176
> Miscellaneous changes deferred from previous PRs

- Gemfile
- Gemfile.lock
- Procfile
- README.md
- Rakefile
- app/mailers/application_mailer.rb
- app/mailers/case_mailer.rb
- app/models/case.rb
- app/views/case_mailer/change_assignee.html.erb
- app/views/case_mailer/change_assignee.text.erb
- app/views/case_mailer/comment.html.erb
- app/views/case_mailer/comment.text.erb
- app/views/case_mailer/new_case.html.erb
- app/views/case_mailer/new_case.text.erb
- app/views/cases/_event.html.erb
- app/views/layouts/case_mailer.html.erb
- app/views/layouts/mailer.html.erb
- app/views/layouts/mailer.text.erb
- bin/start-docker-redis.sh
- bin/stop-docker-redis.sh
- config/application.rb
- config/environments/production.rb
- config/initializers/resque.rb
- config/initializers/resque_mailer.rb
- config/routes.rb
- spec/mailers/case_mailer_spec.rb
- spec/models/case_spec.rb
This PR contains fixes for a number of issues related to emails:
- #189 
- #190 
- #195 
- #199 
- #203 
- #205 
- #212 
- #213 
As part of this, we now require a Redis server as part of a deployment. Notes have been added to `README.md`. There's a one-time setup task required when this gets deployed, to create and configure the Redis server for an environment (I've already done so for staging).
> Miscellaneous email fixes

- docs/design/01-initial-tier-1-tool-planning.md
- docs/design/README.md
I wrote some words on how I plan to implement the MOTD update and user/group management Tier 1 tools, would appreciate any comments/questions/suggestions/pointing out of possible flaws any of you might have :slightly_smiling_face:. Related card: https://trello.com/c/TKgqhL7x/271-request-update-to-motd-tier-1-tool.
> Add design doc for implementing Tier 1 tools

- app/controllers/passwords_controller.rb
- app/mailer_previews/passwords_mailer_preview.rb
- app/mailers/passwords_mailer.rb
Fixes #256, hopefully.
Tested and working in staging.
> Use positional arguments in `PasswordsMailer` method.

- app/controllers/passwords_controller.rb
- app/mailer_previews/passwords_mailer_preview.rb
- app/mailers/passwords_mailer.rb
- fixtures/vcr_cassettes/rt_add_ticket_correspondence.yml
- fixtures/vcr_cassettes/rt_create_ticket.yml
- fixtures/vcr_cassettes/rt_show_ticket.yml
Backport of #259 for next release.
> Use positional arguments in `PasswordsMailer` method. (backport for next release)

- .travis.yml
- bin/setup
- config/initializers/vcr.rb
- lib/tasks/setup.rake
- spec/features/case_form_spec.rb
Trello: https://trello.com/c/tPFr5kG4/299-add-some-case-form-feature-tests. I fully expect this to fail in CI, but let's see how this happens.
> Add some smoke tests that Case form keeps working

- app/views/partials/_flash_alert.html.erb
As title.
Trello: https://trello.com/c/a4nYgNLu/309-fix-squashed-alerts
> Unsquash alerts.

- app/models/case.rb
- app/models/change_motd_request.rb
- app/models/component_group.rb
- app/models/concerns/admin_config/case.rb
- app/models/concerns/admin_config/change_motd_request.rb
- app/models/concerns/admin_config/cluster.rb
- app/models/concerns/admin_config/component.rb
- app/models/concerns/admin_config/component_group.rb
- app/models/concerns/admin_config/log.rb
- app/models/concerns/admin_config/maintenance_window.rb
- app/models/concerns/admin_config/service.rb
- app/models/concerns/belongs_to_cluster.rb
- app/models/concerns/cluster_part.rb
- app/models/concerns/has_state_machine.rb
- app/models/log.rb
- app/models/maintenance_window.rb
- spec/models/component_group_spec.rb
- spec/models/component_spec.rb
- spec/models/concerns/has_state_machine_spec.rb
- spec/models/maintenance_window_spec.rb
- spec/models/service_spec.rb
- spec/support/shared_examples/belongs_to_cluster.rb
- spec/support/shared_examples/is_cluster_part.rb
This PR makes various tweaks and improvements to the admin interface. This includes the changes requested in https://trello.com/c/ucEBWuUw/187-tweaks-to-admin-ui-for-adding-new-nodes-to-existing-cluster, as well several other tweaks (see commits for details).
> Admin interface improvements

- app/controllers/maintenance_windows_controller.rb
Trello: https://trello.com/c/4zYEzkYo/307-address-some-old-pr-comments
It was agreed that there was nothing to actually do on #144!
> Misc tasks from old PR comments

- config/application.rb
> Change `From:` addresses to `alces-flight.com` domain. [backport of #300]

- app/decorators/case_decorator.rb
- spec/features/case/show_spec.rb
> Reword 'commenting disabled because tier' message. [backport of #297]

- README.md
- bin/setup
This PR adds documentation to the README for setting up a development environment and common development tasks. Some of this stuff should be obvious/standard for a Rails app but thought I might as well make things explicit.
@jamesremuscat and @atoghill would you be able to check to see if anything looks unclear/missing/inaccurate to you?
@benarmston barring any needed changes, this should document what you'll need to do to set things up and to do some common development tasks. Let me know and/or fix if anything here doesn't work for you or make sense.
> Document development process

- app/javascript/packs/Cluster.elm
Fix issue where the default charging info would not be displayed when
the saved `chargingInfo` for a Cluster is an empty/just whitespace
string (rather than actually null), even though there's no useful
information to display in this case (this can easily happen through
normal use of the admin interface).
Related card:
https://trello.com/c/ZC3n8Pq8/340-show-default-charging-info-for-any-cluster-with-empty-charginginfo.
> Show default charging info when Cluster's is empty

- app/models/canonical_name_creator.rb
- app/models/case.rb
- app/models/site.rb
- app/models/user.rb
- spec/models/site_spec.rb
- spec/support/shared_examples/canonical_name.rb
Various minor fixes made in the course of making other changes (as part of implementing https://trello.com/c/vezaEjgb/338-update-data-model-with-user-roles); see commits for details.
> Various minor fixes

- Rakefile
- app/models/user.rb
- bin/import-production-data
- lib/deployment.rb
- lib/tasks/data.rake
- lib/tasks/deploy.rake
- spec/lib/tasks/deploy_spec.rb
Several Rake task-related tweaks/fixes made in the course of making other changes, see commits for details.
> Rake task improvements

- Procfile
- bin/backup-database
- lib/deployment.rb
- lib/deployment/crontab.erb
Fixes https://trello.com/c/sJeVgZi7/343-investigate-running-all-some-cron-jobs-in-same-containers; also couple of deployment tweaks included.
> Use single cron container [hotfix]

- app/javascript/packs/Cluster.elm
Backport of https://github.com/alces-software/alces-flight-center/pull/320.
> Show default charging info when Cluster's is empty [backport of #320]

- app/controllers/application_controller.rb
- app/models/user.rb
- spec/features/nav_bar_spec.rb
- spec/models/user_spec.rb
This PR fixes the assignment of scope for viewers, as this should work in the same way as for contacts. Some related refactoring is also included.
> Fix viewer scope

- README.md
- docs/hotfix-release-policy.md
Various documentation changes I've been meaning to make to clarify some things. Please have a skim @jamesremuscat and/or @atoghill and let me know if anything is unclear/doesn't make sense, and merge when ready :slightly_smiling_face:.
> Various docs

- app/models/site.rb
> Don't use `site_case_path` for site users, who don't have `/site` URLs.

- Gemfile.lock
> Update Sprockets to fix security vulnerability.

- app/javascript/packs/View/Charging.elm
- app/models/case_commenting.rb
- app/views/cases/_escalation_controls.html.erb
- spec/features/case/show_spec.rb
This PR adjusts the wording for messages related to tier 3 cases, see #382 for more details.
[Trello](https://trello.com/c/EKkbJ7Rx/375-text-changes-around-tier-3-cases)
> Tier 3 text changes

- app/controllers/case_associations_controller.rb
- app/decorators/cluster_part_decorator.rb
- app/models/slack_notifier.rb
- spec/features/case_associations/edit_spec.rb
As title.
Trello: https://trello.com/c/NKg63t9Q/374-slack-notifications-for-case-association-changes
> Send a Slack notification when case associations are changed.

- app/models/case.rb
- spec/models/case_spec.rb
> Show component groups/components before services in association list.

- app/assets/stylesheets/change_requests.scss
- app/views/change_requests/show.html.erb
This PR makes a few tweaks to the styles of the CR view page to improve readability. (Ref. #422, #423).
Trello: https://trello.com/c/H8n10K6C/383-tweak-cr-page-css
> Improve CR page aesthetics

- app/assets/stylesheets/cases.scss
- app/views/cases/index.html.erb
- app/views/partials/_case_table_row.html.erb
- spec/features/case/index_spec.rb
> Don't highlight resolved "assigned to me" cases

- app/assets/stylesheets/change_requests.scss
- app/assets/stylesheets/markdown.scss
- app/models/concerns/markdown_description.rb
- spec/features/case/show_spec.rb
- spec/support/shared_examples/markdown_column.rb
Actually fixes #422 this time.
> Apply special stylings to all Markdown renderings.

- app/views/partials/_nav_bar.html.erb
> Only show user role in navbar in development / to admins.

- app/controllers/terminal_services_controller.rb
- config/routes.rb
This PR makes it possible to display the error messages requested in https://github.com/alces-software/flight-terminal-services-client/issues/2
> Differentiate error conditions

- app/views/sites/index.html.erb
- app/views/sites/show.html.erb
> Show open cases only at "Manage site cases" / "View cases" links.

- app/assets/stylesheets/markdown.scss
> Updates `code` and `pre` styles to be more pleasing to the eye

- Gemfile
- Gemfile.lock
- app/helpers/mailer_helper.rb
- app/mailers/application_mailer.rb
- app/views/case_mailer/comment.html.erb
- app/views/layouts/mailer/_inline_main.scss
- config/environments/development.rb
- config/routes.rb
> Render markdown content in case comment emails

- app/views/clusters/_credit_charge_entry.html.erb
- spec/features/cluster/credit_usage_spec.rb
Fixes #390.
Trello: https://trello.com/c/MaoR0t6n/408-credit-charges-in-credit-report-should-be-shown-as-positive-values
> change number of spent credits to positive

- app/controllers/case_associations_controller.rb
- app/models/case/associated_model_validator.rb
- spec/features/case_associations/edit_spec.rb
- spec/models/case/associated_model_validator_spec.rb
Porting of #472 to `release/2018.5`.
> Fix/case issue association validation 2018.5

- lib/deployment.rb
> Preserve staging database on deployment

- app/decorators/cluster_decorator.rb
- app/models/cluster.rb
- app/views/clusters/_cluster_checks.html.erb
> Hide checks tab (2018.6 backport)

- app/assets/stylesheets/clusters.scss
- app/views/clusters/_credit_charge_entry.html.erb
- config/initializers/time_formats.rb
Refs #508, needs backporting to release branch.
> Change format of date in credit charge table to that specified in #508.

- app/models/cluster.rb
- app/models/maintenance_window.rb
- spec/features/maintenance_windows_spec.rb
> Multiple maintenance windows fix backport

- app/decorators/case_decorator.rb
Fixes #537.
Trello: https://trello.com/c/Izan0XMK/441-correctly-list-available-issues-for-a-case
> Correctly determine which "Other" issues are suited to a case.

- app/decorators/case_decorator.rb
- app/policies/case_policy.rb
- app/views/cases/_escalation_controls.html.erb
- spec/features/case/show_spec.rb
- spec/policies/case_policy_spec.rb
> Don't show tier or escalation button for admin cases

- app/views/components/index.html.erb
> Sort components by name when listing.

- app/mailers/case_mailer.rb
> Improve admin-detection heuristic to work on staging.

- app/assets/stylesheets/sites.scss
- app/decorators/cluster_decorator.rb
- app/views/sites/_cluster_box.html.erb
> Improve how cluster service plan badge displays on narrow screens.

- db/data/20180831145350_initialise_assigned_contacts_for_open_cases.rb
> Don't try to set an initial contact assignee for administrative cases.

- app/views/cases/_escalation_controls.html.erb
> Hide, not just disable, escalate button for contacts on admin cases.

- app/javascript/View/Charging.elm
Trello: https://trello.com/c/QkqQxo5m/406-change-default-cluster-charging-text
Closes #399
> Change default cluster charging information

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/markdown.scss
Tested with https://upload.wikimedia.org/wikipedia/commons/6/6c/Herjangsfjorden_%26_Ofotfjorden%2C_wide%2C_2009_09.jpg
Closes #559 when merged
> Add css to limit image width in markdown sections
